### ISSUE TITLE
Getting the same sentences multiple times

### ISSUE THREAD

**Issue by a3nm** [mozilla/voice-web#241] opened 2017-06-24 10:57 UTC
As I user, when recording, I often get the same sentences multiple times -- sometimes you can get twice the same sentence in one batch of three recordings.

There should be some way to remember which sentences have already been served to a given session, and not serving them again once they have been recorded.

**Comment by espadrine** [comment] 2017-06-24 15:24
One part of it is that the sentence dataset is really small, at [188 sentences](https://github.com/mozilla/voice-web/blob/master/server/data/funny.txt) (I expected thousands.) May I suggest the use of [Wikisource](https://en.wikisource.org/wiki/Main_Page)? Something speech-heavy, like [Agatha Christie](https://en.wikisource.org/wiki/The_Secret_Adversary), or [modern speeches](https://en.wikisource.org/wiki/Portal:Modern_speeches#2000s), maybe a [play](https://en.wikisource.org/wiki/Porcelain_and_Pink)?

The second part is that it simply uses [`Math.random()`](https://github.com/mozilla/voice-web/blob/master/server/src/lib/api.ts#L22). It [will not yield well-distributed results](http://www.empiricalzeal.com/2012/12/21/what-does-randomness-look-like/), so you risk having a large disparity between the number of recordings per sample. One solution is to increment a global variable on the server, and yield the sentence at that index (and wrapping around, obviously).

**Comment by orschiro** [comment] 2017-07-16 11:03
I think this should be dealt with high priority. If you as an avid and excited user get to see and record the same sentences over and over again, it takes away your motivation to contribute.

**Comment by mikehenrty** [comment] 2017-07-17 14:34
Is this still happening? We have increased our sentences to several thousand (with more coming soon).

(Note, this is not a duplicate of #260, that one is about listening to sentence, this one is about recording. They come from entirely different pools).

**Comment by orschiro** [comment] 2017-07-18 07:51
@mikehenrty I am receiving a lot of new sentences now. Thanks!

**Comment by nmstoker** [comment] 2017-07-18 12:51
Am late to this, but if you're expanding the range of sentences, might be worth considering phonetic pangrams, as by definition these cover a large chunk of sounds quickly (although they are typically unrealistic)

https://www.quora.com/Is-there-a-text-that-covers-the-entire-English-phonetic-range/answer/Sheetal-Srivastava-1

**Comment by a3nm** [comment] 2017-07-18 13:19
I have tried a bit, and it seems like there are now sufficiently many different sentences to avoid getting the same ones multiple times. Thanks for fixing!

**Comment by a3nm** [comment] 2017-07-23 07:35
I'm reopening because the pool of sentences is not so large after all: you can still get the same sentences occasionally when you record a sufficient number of them (around 100), even in the same session.

I think this could be fixed (within one session) by remembering which sentences have already been recorded, and not asking for these same sentences again.

**Comment by Omniscimus** [comment] 2017-07-23 09:00
This will probably be fixed once #304 gets accepted, but before that remembering sentences in a session could be a temporary fix. Allowing users to skip sentences (#278) would probably be a good enough fix as well for now (and skipping would be useful anyway).

**Comment by a3nm** [comment] 2017-07-23 09:11
Skipping sentences would help but it's a bit more tedious, and also as a user I'm not always sure whether I have already seen a sentence or not. (Did I see it when recording, or when validating? Was it that sentence, or another sentence from the same novel? etc.) So even if users can skip sentences there would probably be some frustration and some duplicate recordings (but I don't know whether having duplicate recordings of the same sentence by the same speaker pollutes the dataset).

**Comment by mikehenrty** [comment] 2017-07-25 21:51
Let's close this bug as we are actively trying to gather new sentences in #341. We are increasing our sentences by the day.

**Closed by mikehenrty** 2017-07-25 21:51 UTC
Labels: Browser: All, OS: All, Triage, Type: Enhancement

**Comment by a3nm** [comment] 2018-05-26 09:36
I think this should be reopened: while recording some sentences this morning I got the same one multiple times again. ("Gossips are frogs, they drink and talk", and "Where did he get it", if I remember correctly.)
