### ISSUE TITLE
FF Mobile 57.0.4 cannot validate sentences

### ISSUE THREAD

**Issue by paskalito** [mozilla/voice-web#796] opened 2018-01-05 23:38 UTC
When i try to validate a stenence.
i can listen it. i then get the possibility to choose yes or no.

when i press either of those they get black

nothing more happes no matter how many times i hit it.

![screenshot_20180105-234547](https://user-images.githubusercontent.com/8012793/34633035-a2154936-f279-11e7-9a69-f60cbb7a85d4.png)

i thought there could be something with cookies and stuff so i tried in private mode same result.
Android 7 Galaxy S3 LineageOS
with the standard lineageOS browser i then get a new sentence to validate. ( it works as expected)

**Comment by Gregoor** [comment] 2018-01-06 07:16
Ty for the reminder to deploy it to prod!

Duplicate of #789

**Comment by paskalito** [comment] 2018-01-06 09:33
@Gregoor 

Hi thank you it works now but they are still 2 drawbacks i found:

- i need to click twice on the yes/no buttons
- backgroud loading of the next sentence is not working.

both behaves as is should (i guess) in the system browser and boy the background loading thing makes validating SO much faster ! :)

**Comment by Gregoor** [comment] 2018-01-06 10:02
@paskalito thanks for re-checking it and getting back to me. I really shouldn't rely on the FF mobile emulator.

RE background loading, it is working on FF mobile but for some reason cache hits take a bit longer on FF.

**Comment by Gregoor** [comment] 2018-01-08 11:27
Didn't find a good reason why FF mobile behaves that way (and FF desktop touch emulator behaves correctly). I just attached an onTouchStart listener which fixes the problem for now.

**Closed** 2018-01-08 11:26 UTC

**Comment by paskalito** [comment] 2018-01-22 21:47
thanks i also think it worked once for some timeframe, but now i doesn't come to the point anymore where i can hit the play button at all..
