### ISSUE TITLE
Expose progress of data collection some how

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/voice-web#380] opened 2017-07-28 22:59 UTC
For example: https://location.services.mozilla.com/stats

It can be motivating for users to see how much data has been collected.

**Comment by Omniscimus** [comment] 2017-07-29 06:41
This was planned in #262 :smile:

**Comment by mikehenrty** [comment] 2017-09-27 15:04
Yup, duplicate of #262.

**Closed by mikehenrty** 2017-09-27 15:04 UTC
