### ISSUE TITLE
When validating, make it clearer when sound is actually playing

### ISSUE THREAD

**Issue by a3nm** [mozilla/voice-web#282] opened 2017-07-18 13:48 UTC
In some cases (network problem?), when clicking on the play button to listen to a sentence for validation, no sound is actually played. However, the button still changes to "pause", giving the impression that the sentence is currently playing (and never changes back to play). This is problematic because a validator would then reject the sentence, thinking that it is silent, whereas actually the problem is elsewhere.

It would be preferable for the "play" button to change to something else (e.g., a loading animation) when playback has been requested but hasn't started yet.

**Comment by mikehenrty** [comment] 2017-07-19 09:10
My guess is that what you are seeing is when someone recorded a silent clip. I've done it myself a few times, where I actually had my mic muted but thought I was recording anyway. If there was a network error, the whole play box would be grayed out. I'm not sure there is anything we can do here about silent clips. What do you think @a3nm ?

**Comment by a3nm** [comment] 2017-07-19 09:19
I think silent clips should be filtered out automatically without human validation, which is related to #279.

As for network errors, indeed it seems that the utterance is downloaded before the controls are displayed, so what I had been experiencing probably wasn't network-related. Maybe it was a problem with my headset, in which case there's little that can be done...

That said, I recall that the "pause" button was not disappearing after some time, so either the utterance was very long or something else was going on. This is vague though, so maybe this can be closed, and I can complain here again if the phenomenon occurs again.

**Comment by mikehenrty** [comment] 2017-07-19 09:53
Ok, let's close this for now assuming these are just long silent recordings, and track the filtering of silent clips in 279 as you mentioned.

If further evidence comes out that this is not caused by a silent recording, let's reopen and investigate further.

**Closed** 2017-07-19 18:59 UTC
