### ISSUE TITLE
Html tags in speech text

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#858] opened 2018-02-10 09:15 UTC
Looks like a bug to me:
(was the same string the person saw while recording though, I think)
![screenshot_20180210-101316](https://user-images.githubusercontent.com/5685512/36060509-3b6458b0-0e4b-11e8-9887-5eadf10e196c.png)

**Comment by Djfe** [comment] 2018-02-10 09:31
similar (no audio was audible on reviewing and the button got reset after 1s):
![screenshot_20180210-102930](https://user-images.githubusercontent.com/5685512/36060608-778a7c14-0e4d-11e8-959b-61cca0d07779.png)

**Comment by Gregoor** [comment] 2018-02-10 12:24
the former is probably some old clip that needed your final no-vote, the latter is a duplicate of #853

**Closed** 2018-02-10 12:27 UTC
