### ISSUE TITLE
“Undefined” in sentence field when validating recordings

### ISSUE THREAD

**Issue by adamaze** [mozilla/voice-web#853] opened 2018-02-08 04:46 UTC
I validated about 300 recordings today using the iOS app, and have found a handful of times where the text box simply says “undefined” instead of the spoken sentence.

**Comment by jf99** [comment] 2018-02-08 20:29
Duplicate of #338.

**Comment by Gregoor** [comment] 2018-02-09 09:18
Hi adamaze, thank you for all these contributions 👍
Actually #338 should be fixed by now and I don't find data in the DB where the sentence would be empty. I think this might be a FE bug, but so far I haven't found a way to reproduce it.

**Comment by jf99** [comment] 2018-02-09 11:07
> so far I haven't found a way to reproduce it.

I just validated 150 sentences and had 5 "undefined" ones. So at least for me, it's one of thirty. I have the impression, that wrongly read sentences get presented for validation more often than others. This is probably why "undefined" appears so often.

**Comment by Gregoor** [comment] 2018-02-10 12:40
Oh, I misunderstood the hint with the db. There are actually 710 recordings where the sentence is literally "undefined". Should we just throw them out @mikehenrty?

**Comment by mikehenrty** [comment] 2018-02-12 12:26
Let's not throw out any data. Even "invalid" data could be useful to speech researchers, and it's worth going throw the validation step to see if they actually said "undefined."

@Gregoor are we continuing to get new ones with "undefined" going in? Ie. has the 710 number gone up?

**Comment by Gregoor** [comment] 2018-02-12 13:05
Gotcha makes sense, @mikehenrty. I don't think it has gone up. I'll keep an eye on it!

**Closed** 2018-03-07 13:00 UTC
Labels: Type: Bug
