### ISSUE TITLE
Null validation sentence.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#271] opened 2017-07-17 15:53 UTC
This old bug still appears to be happening.

![image](https://user-images.githubusercontent.com/311082/28276992-5e6191ba-6acd-11e7-9019-ba19cc32dd00.png)

**Comment by mbebenita** [comment] 2017-07-17 15:56
This is always happening for me at the moment, in every browser.

**Comment by andrenatal** [comment] 2017-07-17 16:18
For me too:

<img width="1389" alt="screenshot 2017-07-17 09 17 07" src="https://user-images.githubusercontent.com/973388/28278137-d95cef42-6ad0-11e7-8567-2bd6c4dff016.png">

**Comment by mikehenrty** [comment] 2017-07-17 17:20
@mbebenita @andrenatal: should be fixed with the latest deployment. are you still seeing this issue?

**Comment by kdavis-mozilla** [comment] 2017-07-17 17:23
I'm not seeing it any more! :-)

**Comment by Omniscimus** [comment] 2017-07-17 17:25
It's fixed for me as well :smile:

**Comment by mikehenrty** [comment] 2017-07-17 17:31
Let's close this for now. Feel free to re-open if the problem is still happening, or resurfaces.

**Comment by mbebenita** [comment] 2017-07-17 17:33
What was the problem? And, is it likely to surface again?

**Comment by mikehenrty** [comment] 2017-07-17 17:45
The server was returning 500 errors when trying to fetch a random clip, which was mostly likely due to inconsistent data in the servers memory compared in S3. I believe @kdavis-mozilla had actually fixed this issue a while back in 94ab7fc209d3ef1179ed9d6d1f56d6d86680a27b, but we were waiting until the snippet campaign ran it's course to deploy (since it had been at least working up until today). Once listening stopped working altogether on the live site, I decided it was worth the risk to do a deploy (even though we had 60 live users on the site at the time). Everything appears to be working normally now.

**Comment by Omniscimus** [comment] 2017-07-17 17:59
It's actually still happening sometimes for me. After reviewing some 5 recordings, I get the same as OP's screenshot. Also the server seems to be down for me after that for a while, is this related? Once I got a blank page, once a 503 error...

**Comment by mikehenrty** [comment] 2017-07-17 18:07
Let's keep an eye on this. Those 503 errors happen when our system detects too much load and begins adding more servers to our deployment cluster to compensate. This can also cause the "Null" error reported here for the same reasons. Once the system stabilizes (which should only take a few minutes), we'll know if this problem is still happening.

**Comment by mbebenita** [comment] 2017-07-17 19:00
Can we at least show something other than "null" in case of an error? Maybe, something about how the system is really busy.

**Comment by mbebenita** [comment] 2017-07-19 17:23
I just tried this again, and after validating one sentence I saw `null`, so this bug appears to be unresolved.

**Comment by mikehenrty** [comment] 2017-07-19 18:03
Just fixed the error message part in https://github.com/mozilla/voice-web/commit/e8cd1e7664908f0972e1a788974dee39b7b68a8e. So even if the server completely falls over, the user will know we are having troubles rather than seeing null.

**Closed by mikehenrty** 2017-07-19 18:03 UTC
Labels: engineering, Priority: P1
