### ISSUE TITLE
Some Recordings are too quiet

### ISSUE THREAD

**Issue by paskalito** [mozilla/voice-web#1899] opened 2019-03-17 15:00 UTC
So you cannot hear them.

there was a solution implemented to level out volume difference on the listeners side. what happened to that? ( or was it only working for samples too loud)

related thing i found
https://github.com/mozilla/voice-web/issues/1510

**Comment by Gregoor** [comment] 2019-03-20 11:44
Heya, so yes someone from the community built something that would normalize the volume. Unfortunately it had problems in Safari. But they turned it into an extension, which you can find here:
https://send.firefox.com/download/b6e45f6a5d/

**Comment by MichaelNMaggs** [comment] 2019-05-06 14:02
Duplicate of #1498

**Closed** 2020-02-22 01:33 UTC
