### ISSUE TITLE
Indicate whether non-native English accents are welcome

### ISSUE THREAD

**Issue by Vinnl** [mozilla/voice-web#391] opened 2017-07-31 18:55 UTC
The voice.mozilla.org website doesn't really mention if non-native English accents are welcome or not, but when I go to the profile page, I cannot indicate that I have a Dutch accent. So either it should be clarified that that's not welcome, or perhaps an option "non-native" should be added :)

**Comment by Omniscimus** [comment] 2017-07-31 19:23
A non-native option has already been added (99e7d7b4c21d5a0890823f97067559798536ebf8), but apparently the production website is slightly behind. It will probably be there soon!

**Comment by Vinnl** [comment] 2017-07-31 19:26
Well that was fast, thanks!

**Comment by mikehenrty** [comment] 2017-08-03 10:10
Let's use #242 to track the work here, since we've recently re-opened that.

Duplicate of #242.

**Closed by mikehenrty** 2017-08-03 10:10 UTC

**Comment by nukeador** [comment] 2019-05-14 20:26
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
