### ISSUE TITLE
UX: It is unclear, what a validation "No" means 

### ISSUE THREAD

**Issue by jdittrich** [mozilla/voice-web#284] opened 2017-07-18 17:37 UTC
## Problem for the user

It is unclear in which cases I shall click "No". Here are some in which I have been unsure:

1. The speaker was understandable, but had a heavy accent
2. The speaker pronounced everything correctly, but there is a lot of background noise
3.  The speaker accidentally misread a word and repeated it correctly again. 
## Problem of the Interface
It is not said what we ask for. It says "validate" – but on what criteria?

## Possible Actions:  

* clarify what the yes/no refers to,e.g. by asking:
    * Is this sentence correct and free of problems? (All examples above would be a *no* then)
    * Was the same sentence read? (All examples above would be a *yes*, if the same sentence was read)
    * Was the audio of good quality? (1. and 3. would be yes, 2. not)
* We have the buttons "fine" and "had problems" 
    * …and we possibly allow to specify the problem after clicking "had problems": "What was probematic? Choose from this list" (similar to what http://www.alternativeto.net does when I click "not an alternative" )

**Comment by Omniscimus** [comment] 2017-07-18 17:49
Duplicate of #273

**Comment by jdittrich** [comment] 2017-07-18 17:59
@mikehenrty wrote in 273: 

>  If the spoken sentence is even off by 1 word, it's invalid. We need to make that clear in the description.

**Comment by mikehenrty** [comment] 2017-07-19 09:23
Yeah, let's close this in favor of 273. But thanks for your thoughts here Jan!

**Closed by mikehenrty** 2017-07-19 09:23 UTC
