### ISSUE TITLE
Numbers don't fit in the fields

### ISSUE THREAD

**Issue by deevroman** [mozilla/voice-web#2835] opened 2020-07-18 16:01 UTC
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0
<img width="1203" alt="Снимок экрана 2020-07-18 в 18 49 44" src="https://user-images.githubusercontent.com/25708359/87856627-fb499600-c928-11ea-8d35-f59dd48c4ca3.png">

**Comment by phirework** [comment] 2020-07-24 21:50
Hello, thanks for reporting this! This is a duplicate of #2790 and we are working on a fix. I'm going to close this one, please direct any additional discussions there.

**Closed by phirework** 2020-07-24 21:50 UTC
