### ISSUE TITLE
[verification] Sometimes the same recording is shown twice in a row

### ISSUE THREAD

**Issue by jf99** [mozilla/voice-web#1362] opened 2018-08-15 19:52 UTC
I think this only happens on the listen page, not on the home page. Sometimes recording 5 of a validation series is equal to recording 1 of the next series. This happened like five times to me until now. It's always the first of one series and the last of the previous one. Contrary, recording no. 3 is never equal to no. 2, for example.

**Comment by mikehenrty** [comment] 2018-09-05 15:11
@jf99 is this a duplicate of #1220?

**Comment by jf99** [comment] 2018-09-07 19:53
@mikehenrty No, #1220 is about recording. This issue is about listening. I noticed that sometimes it also happens that the last **two** of a row get repeated in the next row.

**Comment by jf99** [comment] 2018-09-08 12:52
I think my explanation might still be a bit unclear. So I made a video. It happened about every 5 minutes, but I deleted most of the time in between for you. Sorry for the flickering caused by my recording software.
[listening.mkv.zip](https://github.com/mozilla/voice-web/files/2363309/listening.mkv.zip)

**Comment by danielsjf** [comment] 2018-10-09 19:18
I have the same problem. Sometimes it even happens for more than one sentence (two or three are repeated).

**Comment by flyingpimonster** [comment] 2018-12-02 01:19
This is currently happening to me every time I move to a new set of 5--the last sentence of one set is the same as the first sentence of the next.

**Comment by Gregoor** [comment] 2018-12-03 19:43
@flyingpimonster I think this might be the same issues as here #1659

**Comment by MichaelKohler** [comment] 2020-02-21 23:55
I'm closing this, if this is still happening please reopen :)

**Closed by MichaelKohler** 2020-02-21 23:55 UTC
