### ISSUE TITLE
Inconsistency between points displayed in Team Progress vs "My points"

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2337] opened 2019-11-15 13:45 UTC
[STR]:
1.Go to https://voice.allizom.org/en/dashboard/challenge

[Expected result]:
Should have the same points no. in Team Progress and "My points"

[Actual result]:
Inconsistency between point displayed in Team Progress vs "My points"

![2019-11-15_15h42_58](https://user-images.githubusercontent.com/41474886/68947737-dd86c880-07be-11ea-9fff-934a0ec06c1c.png)

![2019-11-15_14h55_45](https://user-images.githubusercontent.com/41474886/68947754-e5df0380-07be-11ea-9326-f63a5641ae15.png)

**Comment by mbransn** [comment] 2019-11-15 19:01
Is this due to the leaderboard cache 20 min lag? cc @rileyjshaw

**Comment by rileyjshaw** [comment] 2019-11-16 16:37
Definitely seems like it could be! @rleitan, would you mind waiting half an hour and checking if the points equalize?

**Comment by can-007** [comment] 2019-11-16 18:01
I wanted to point out that “recorded” tab shows the clip points + bonus and the “validated” tab shows the vote points + bonus.
So it is not so obvious.

**Comment by mbransn** [comment] 2019-11-18 18:32
Correct, expected is actually: 
`My points` = the sum of `Recorded` + `Validated` point totals.

I've just submitted 10 recorded clips on production in my test challenge account:
- Header clip counter is reflecting that 10 clip total immediately
- `My points` is not reflecting 10 points immediately, will check back in 20 mins
- Challenge individual clip counter is not reflecting 10 recordings immedatiately, will check back in 20 mins

<img width="1434" alt="Screen Shot 2019-11-18 at 10 30 14 AM" src="https://user-images.githubusercontent.com/18686986/69079381-b6aed900-09ee-11ea-9c79-cd0311ab9f3d.png">

**Comment by mbransn** [comment] 2019-11-18 19:20
Checked at 20 mins and again at 1hr, still no reflection of points for contribution on either current challenge card or team leaderboard. @LRSaunders4 can you please test this and confirm if you're receiving points immediately on your test contributions?

**Comment by LRSaunders4** [comment] 2019-11-18 19:43
Just listened to 5 clips and recorded 5 clips. Both went through as submitted under Lindsay Test 2 but I do not see them reflected in my team leaderboard points. I have not seen the challenge card move in any testing I have done.

**Comment by mbransn** [comment] 2019-11-18 20:29
@rileyjshaw is this something @can-007 and/or @catherine917 can help out with today when they come online?

**Comment by rileyjshaw** [comment] 2019-11-18 20:57
Yes, that sounds like a great match. @can-007 @catherine917, I'm assigning you both to this issue!

**Comment by can-007** [comment] 2019-11-19 07:28
I see that this is happening on prod server, and all the contributions and bonus are recorded in database.
I run the related SQL against the prod database and find the points are correct.
I also contributed 6 votes, waited for 20 minutes, and found my points reflected the contribution I just made.

@mbransn , could you please check again that if your points are 60?

**Comment by mbransn** [comment] 2019-11-19 07:48
@can-007 confirmed that my points on prod are now 60 and show accurately for my dashboard and leaderboard. I’ve contributed two validation clips at 23:45 and do not see the two points reflected on my dashboard even though the header stat counter is updated. I understand the leaderboard cache, but do not understand why this is also affecting the point system itself.

cc @rileyshaw @phirework

**Comment by rileyjshaw** [comment] 2019-11-19 18:07
I believe this was fixed in https://github.com/mozilla/voice-web/commit/8776c09aa799b85b65b969f8b70b5f8322255489. Awaiting confirmation.

**Comment by mbransn** [comment] 2019-11-19 23:38
Confirmed fixed!

**Closed by mbransn** 2019-11-19 23:38 UTC
Labels: Priority: P1, RESOLVED: awaiting confirmation, voice-challenge
