### ISSUE TITLE
Please include the source of the text in the FAQ

### ISSUE THREAD

**Issue by Kusaha** [mozilla/voice-web#306] opened 2017-07-20 15:29 UTC
I was wondering what book (or else) are we using for the sentences, it would be nice if you would include the source text in the FAQ or at least the books title.

**Comment by Omniscimus** [comment] 2017-07-20 16:43
Duplicate of #287

**Comment by DeathCamel57** [comment] 2017-07-23 03:17
Here's where the text is located.

- [voice-web/server/data/temporary-sentences.txt](https://github.com/mozilla/voice-web/blob/master/server/data/temporary-sentences.txt)
- [voice-web/server/data/temporary-sentences-2.txt](https://github.com/mozilla/voice-web/blob/master/server/data/temporary-sentences-2.txt)
- [voice-web/server/data/funny.txt](https://github.com/mozilla/voice-web/blob/master/server/data/funny.txt)
- [voice-web/server/data/new-sentences.txt](https://github.com/mozilla/voice-web/blob/master/server/data/new-sentences.txt)

**Comment by DeathCamel57** [comment] 2017-07-23 03:30
Now to see if the pull request is accepted.

**Comment by DeathCamel57** [comment] 2017-07-23 21:16
New pull (#330) should fix this.

**Comment by mikehenrty** [comment] 2017-07-24 00:37
We swapped out those books for contributor donated sentences, and some public domain screenplays like _It's a Wonder Life_. We now document this in our faq, thanks to @DeathCamel57's PR. Closing.

**Closed by mikehenrty** 2017-07-24 00:37 UTC
