### ISSUE TITLE
"Recording was too long" message cuts in too quickly

### ISSUE THREAD

**Issue by MichaelNMaggs** [mozilla/voice-web#805] opened 2018-01-15 10:43 UTC
It's not possible to record some of the longer sentences, as the "recording was too long" message prevents it. One example sentence that I'm not able to record is this one:

- "The closet door stuck a little as he pulled it open revealing a bare wooden floor covered on one side by a stack of old shoes boxes."

I'm using Firefox Quantum 57.0.4 on a Mac, if that's helpful

**Comment by Gregoor** [comment] 2018-01-15 14:55
Duplicate of #779 

(The naming of #779 was misleading and hence probably hard to find, I just renamed it a bit)

**Closed by Gregoor** 2018-01-15 14:55 UTC
