### ISSUE TITLE
An error occurred when reloading the dashboard page

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2404] opened 2019-11-21 10:25 UTC
[STR]:
1.Login with an account already registered to voice challenge
2.Click reload button -> from dashboard

[Actual result]:
"An error occurred" message is displayed
https://drive.google.com/file/d/13c3_0rNfq6CKULfQuvWVsTX6InszvyB9/view?usp=sharing

**Comment by phirework** [comment] 2019-11-21 18:38
I think #2400 also incidentally fixed this. Can you test on voice.allizom.org to see if it's reproducible there?

**Comment by rleitan** [comment] 2019-11-22 08:58
I can reproduce it on  voice.allizom.org.

**Comment by rleitan** [comment] 2019-11-25 17:10
I reproduced it on Windows 10- Edge 
Console error: TypeError: Unable to get property 'done' of undefined or null reference
![2019-11-25_19h09_12](https://user-images.githubusercontent.com/41474886/69562054-1260ff80-0fb7-11ea-8e7d-6667c0edd968.png)

**Comment by mbransn** [comment] 2019-12-02 21:34
Looks like this is resolved, @phirework can you confirm?

**Comment by phirework** [comment] 2019-12-02 22:42
Confirmed fixed in #2307

**Closed** 2019-12-02 22:42 UTC
Labels: Priority: P1, voice-challenge

**Comment by viorelaioia** [comment] 2019-12-09 15:27
I managed to reproduce this again in prod, by being inactive on the dashboard page for several  minutes, then clicking "Contribute" button.

![error on cv](https://user-images.githubusercontent.com/5293100/70448299-d6469800-1aa8-11ea-8694-6be0e3922075.png)
