### ISSUE TITLE
Mobile Firefox Doesn't Always Show Entire Prompt in Landscape View

### ISSUE THREAD

**Issue by webstrand** [mozilla/voice-web#1198] opened 2018-07-01 23:46 UTC
I am using a Gemini PDA which has an odd form factor. The prompt text is sometimes not shown in its entirety when the browser's collapsable address bar is not collapsed. It is easy to accidently truncate a prompt when speaking.

**Comment by mikehenrty** [comment] 2018-07-02 10:23
@webstrand any chance you could give us a screenshot?

**Comment by webstrand** [comment] 2018-07-02 21:04
![screenshot_20180702-170122](https://user-images.githubusercontent.com/373938/42186207-b6699b90-7e19-11e8-8fd3-aef7c098c8b8.png)

The full prompt should be, "Everyone else is smarter than me, and there's only 12 positions across the whole uni."

**Comment by mikehenrty** [comment] 2018-07-03 08:58
This is great @webstrand, let's close this one as a duplicate of #1180, but I will copy your screenshot over there.

**Closed by mikehenrty** 2018-07-03 08:58 UTC
