### ISSUE TITLE
"undefined" when listening

### ISSUE THREAD

**Issue by rugk** [mozilla/voice-web#338] opened 2017-07-23 16:17 UTC
![grafik](https://user-images.githubusercontent.com/11966684/28501011-033b90fa-6fd3-11e7-837b-3e2e9c83127a.png)

This is what I got with a short 3 sec sound only rustling.

**Comment by mikehenrty** [comment] 2017-07-23 17:02
Duplicate of #300. These are just leftover recordings from an earlier bug, and they are actually not bad if the user actually does say "undefined"

**Closed by mikehenrty** 2017-07-23 17:02 UTC
