### ISSUE TITLE
English accent list is too limited, no proper foreign speaker options are available (e.g. American English with German accent, ..)

### ISSUE THREAD

**Issue by JonasT** [mozilla/voice-web#334] opened 2017-07-23 13:51 UTC
The profile box for English accent is too limited, no proper foreign speaker options are available (e.g. American English with German accent, ..). Listening through the examples it seems that at least a tenth of them are from foreign speakers, so the profile options really should be updated to be able to properly specify your native languages and whether you speak English just as a foreign language.

**Comment by Omniscimus** [comment] 2017-07-23 13:53
Duplicate of #242

**Comment by mikehenrty** [comment] 2017-07-23 15:22
Yup, let's use 242 to track this.

Duplicate of #242.

**Closed by mikehenrty** 2017-07-23 15:22 UTC

**Comment by nukeador** [comment] 2019-05-14 20:26
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
