### ISSUE TITLE
Tapping yes/no brings up context menu

### ISSUE THREAD

**Issue by contrapunctus-1** [mozilla/voice-web#803] opened 2018-01-14 06:11 UTC
Firefox Nightly on Android, v59.0a1
(2018-01-13)

Tapping Yes or No even slightly brings up the "Select All" context menu, and the Yes/No is accepted immediately (earlier it'd turn black and require one more tap to confirm).

This wasn't happening a few days ago. Not sure if this is a website or a browser issue.

**Comment by mikehenrty** [comment] 2018-01-29 14:48
@contrapunctus-1 are you still seeing this?

@Gregoor can you reproduce?

**Comment by contrapunctus-1** [comment] 2018-01-29 22:00
@mikehenrty yeah, I am. v60.0a1 (2018-01-29)

**Comment by Djfe** [comment] 2018-02-11 22:54
I can confirm this (current release android Firefox)
And button feedback would certainly be helpful :)

**Comment by Gregoor** [comment] 2018-02-12 11:25
I'm still puzzled by this. Anyone got an idea why that happens?

**Comment by Djfe** [comment] 2018-02-15 09:06
maybe it's a bug in Firefox.
Now it's happening for me as well, when I click the checkboxes on Doodle.com (wasn't happening before)
(the 3 state custom checkboxes: yes, maybe, no)

**Comment by Gregoor** [comment] 2018-12-13 15:09
Looks like it was fixed in Firefox!

**Closed by Gregoor** 2018-12-13 15:09 UTC
Labels: Type: Bug, help wanted

**Comment by Djfe** [comment] 2018-12-14 09:40
In-case you're interested:
partially
https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1464792

but since it's fixed on common voice by now, it can be safely closed here :)
