### ISSUE TITLE
Capital Is and small Ls are exactly the same in the used font

### ISSUE THREAD

**Issue by stefangrotz** [mozilla/voice-web#2561] opened 2020-02-10 21:53 UTC
I have seen a some wrongly recorded donations because the font (is it zilla slab?) has identical looking capital Is and small Ls.  For example in Esperanto there is the word "la" (the) and the word "ia" (any) and people sometimes mix them up when they are at the beginning of a sentence or when both words are grammatically possible.

<img width="291" alt="Bildschirmfoto 2020-02-10 um 22 53 31" src="https://user-images.githubusercontent.com/5982239/74193752-34822980-4c58-11ea-891d-dc5bdea8f108.png">

This is also sometimes confusing when you review sentences.

**Comment by MichaelKohler** [comment] 2020-02-22 02:49
Thank, I'll close this as a dupe of https://github.com/mozilla/voice-web/issues/2081

**Closed by MichaelKohler** 2020-02-22 02:49 UTC
