### ISSUE TITLE
Clicking yes or no does not do anything: i.user.account is null

### ISSUE THREAD

**Issue by rugk** [mozilla/voice-web#2459] opened 2019-12-07 15:09 UTC
## STRs

1. Go to https://voice.mozilla.org/de/listen
2. Click "Yes" (or "No")

What happens: Nothing.

What should happen: Show me next sentence.

Console:
```
16:05:51.435 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). 2 utils.js:35:9
16:05:51.448 do not track header set, disabling analytics listen:65:17
16:05:51.457 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). listen:107:1
16:05:51.512 Intl.PluralRules already exists, and has NOT been replaced by this polyfill polyfill.js:92:12
16:05:51.512 To force, set a global ClobberIntlPluralRules = true polyfill.js:93:12
16:05:51.623 Error: Cannot load extension settings keepassxc-browser.js:828:17
16:06:04.582 TypeError: i.user.account is null
clips.ts:127:10
16:06:13.296 Error: Cannot load extension settings
```

## Additional information

When I once reloaded the site in this state, I got an empty white page "an error occured", and could create a Senetry error report.

Firefox 71

**Comment by popey** [comment] 2019-12-09 09:48
Confirmed broken here in chrome and firefox 70.

**Comment by dabinat** [comment] 2019-12-09 18:06
I’m seeing similar issues on my iPhone (iOS 13.2.3). Instead of being instant, tapping Yes/No takes about 2 seconds for the next sentence to appear. And sometimes it does nothing at all no matter how many times I tap the buttons.

Also, sometimes tapping Play cuts off the recording because it appears to interpret it as two taps.

**Comment by phirework** [comment] 2019-12-09 20:54
Thanks for the report, folks. Can you still reproduce the issue?

**Comment by popey** [comment] 2019-12-09 21:46
@phirework all good new in Firefox 70. Thanks.

**Comment by dabinat** [comment] 2019-12-11 19:07
@phirework This issue appears to have returned. The buttons are not doing anything again.

**Comment by phirework** [comment] 2019-12-11 20:02
@dabinat Thanks for the flag! Trying to track it down in our error logs, were you voting on french clips by any chance?

**Comment by dabinat** [comment] 2019-12-11 20:33
@phirework No, I only validate English. If it helps track it down, I’m on an iPhone 8 running iOS 13.2.3, using Firefox as my browser and my IP is located in Los Angeles, California. I was logged into my account at the time (dabinat).

**Comment by phirework** [comment] 2019-12-11 20:47
Awesome, thanks for the extra detail.

**Comment by phirework** [comment] 2019-12-11 23:55
@dabinat Did you happen to catch if your console also spat out an `user.account is null` error or if it just sat there and didn't do anything at all?

**Comment by dabinat** [comment] 2019-12-12 05:40
@phirework Unfortunately because I’m on an iPhone, I would have had to have tethered it to a computer to see that information.

I tried doing that but now it appears to be working and I can’t reproduce it. I’ll let you know if it comes back.

**Comment by dabinat** [comment] 2019-12-17 20:23
@phirework I had this issue again today. Unfortunately it took me a while to get my phone properly working with the remote debugger and by the time I did, it had started working again.

However, even with it working properly, I still got a bunch of errors related to the load balancer timing out, which could be related to the original issue:

```
[Error] Failed to load resource: the server responded with a status of 504 (GATEWAY_TIMEOUT) (leaderboard, line 0)
[Error] Unhandled Promise Rejection: Error
	generatorResume (bundle.js:68:10495)
	s (5.bundle.js:1:10132)
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 504 (GATEWAY_TIMEOUT) (voices, line 0)
[Error] Unhandled Promise Rejection: Error
	generatorResume (bundle.js:68:10495)
	s (6.bundle.js:8:4777)
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 502 (Proxy Error) (clips, line 0)
[Error] Unhandled Promise Rejection: Error: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>

	generatorResume (bundle.js:68:10495)
	l (bundle.js:1:105957)
	promiseReactionJob
```

I've noticed the buttons not working problem seems to occur more often in the mornings for me (GMT -8) so I wonder if it is related to how busy the site is?

**Comment by phirework** [comment] 2019-12-19 18:41
@dabinat Thanks so much for following up and providing all the debugging info! It's definitely related to server load, which is also why it's been super frustrating to troubleshoot. We're in the middle of a couple of db optimization things that I think will help a lot, so I will continue to keep an eye on this bug.

**Comment by phirework** [comment] 2019-12-30 20:37
@dabinat We've made a bunch of performance optimizations in the last week or so and Sentry no longer seems to be picking up this error, have you experienced this again recently? If not, feel free to close this issue :) Thanks!

**Comment by dabinat** [comment] 2019-12-30 21:02
@phirework Yes, not only have I not experienced this issue in a while, but there is also no lag when pressing the buttons now. Thanks!

**Closed** 2019-12-31 16:46 UTC
