### ISSUE TITLE
Error when validating samples

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voice-web#188] opened 2017-06-19 23:43 UTC
I got this error in my third sample:

<img width="1134" alt="screenshot 2017-06-19 16 41 51" src="https://user-images.githubusercontent.com/973388/27310332-5b8b9dac-550e-11e7-860f-5b3e59ba03d7.png">

**Comment by kdavis-mozilla** [comment] 2017-06-20 05:17
What's your userid?

**Comment by andrenatal** [comment] 2017-06-20 06:13
1 - http://voice.mozilla.org/
2 - Firefox Dev Edition

**Comment by kdavis-mozilla** [comment] 2017-06-20 09:36
Was able to repo. I'll explore more.

**Comment by kdavis-mozilla** [comment] 2017-06-20 10:34
Just tried 100 times for a reproduction on localhost and couldn't reproduce it.
Just tried 100 times for a reproduction on staging and couldn't reproduce it.
Just tried 100 times for a reproduction on production and couldn't reproduce it.

My guess is that it's servers in the elastic group spinning up or down.

**Comment by paulsilaghi** [comment] 2017-06-21 10:09
Just got a 'null' sample on https://voice.allizom.org.
Chrome 59, Win 10.
![null listen](https://user-images.githubusercontent.com/29535384/27379142-d2abbc08-5682-11e7-8d2b-e05753629c51.png)

**Comment by kdavis-mozilla** [comment] 2017-06-21 10:34
@paulsilaghi Did you have this happening more than once?

**Comment by paulsilaghi** [comment] 2017-06-21 11:57
Yes, reproduced again after validating ~50 recordings.

**Comment by kdavis-mozilla** [comment] 2017-06-21 12:53
@paulsilaghi I'm not sure if this is a code bug or infra bug as staging over the last 2-3 hours has been failing.

**Comment by andrenatal** [comment] 2017-06-21 16:43
Just got this issue too in my first sample.

**Comment by kdavis-mozilla** [comment] 2017-06-21 16:49
@andrenatal Which issue? `null` or `undefined`? Which server too.

**Comment by andrenatal** [comment] 2017-06-21 17:15
Firefox for Android
voice.mozilla.org

![screenshot_20170621-094032](https://user-images.githubusercontent.com/973388/27397220-6f4323da-566a-11e7-9a93-b9080d3d5d87.png)

**Comment by mikehenrty** [comment] 2017-06-23 16:58
hopefully this will be fixed in#193

**Comment by kdavis-mozilla** [comment] 2017-06-24 10:50
@andrenatal @paulsilaghi This should be fixed with commit 617d796 

If you see either issue here again please re-open.

**Closed by kdavis-mozilla** 2017-06-24 10:50 UTC
Labels: Priority: P2, Triage, Type: Bug
