### ISSUE TITLE
Web code style: Use async/await?

### ISSUE THREAD

**Issue by kenrick95** [mozilla/voice-web#402] opened 2017-08-05 04:44 UTC
Would you like to try changing the coding style from using Promise.then into async/await? Thanks

One example of change (on src/lib/api.ts):

```ts
private getRandomSentences(count: number): Promise<string[]> {
  return this.getSentences().then(sentences => {
    let randoms = [];
    for (var i = 0; i < count; i++) {
      let distribution = Random.integer(0, sentences.length - 1);
      let randomIndex = distribution(this.randomEngine);
      randoms.push(sentences[randomIndex]);
    }
    return randoms;
  });
}
```

become:

```ts
private async getRandomSentences(count: number): Promise<string[]> {
  const sentences = await this.getSentences();
  let randoms = [];
  for (var i = 0; i < count; i++) {
    let distribution = Random.integer(0, sentences.length - 1);
    let randomIndex = distribution(this.randomEngine);
    randoms.push(sentences[randomIndex]);
  }
  return randoms;
}
```

**Comment by mikehenrty** [comment] 2017-08-05 11:00
I definitely want to! Looking at [caniuse](http://caniuse.com/#feat=async-functions), it seems less than 70% of the global audience supports this feature yet, so it might be a bit soon for this. What do you think @kenrick95?

**Comment by kenrick95** [comment] 2017-08-05 13:23
Since we are using [TypeScript ^2.3.4](https://github.com/mozilla/voice-web/blob/master/package.json#L35) and [targeting transpilation to ES5](https://github.com/mozilla/voice-web/blob/master/web/tsconfig.json#L3), I think we are fine, because TypeScript, since [v2.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#downlevel-async-functions) will generate ES5-supported codes for async functions (although we still might need to add a polyfill for Promise)

**Comment by nevik** [comment] 2017-08-13 06:33
But adding a Promise polyfill or not is independent from using TS async/await.
This TS feature is syntactic sugar only, so it would be great to start using it 👍

**Comment by nevik** [comment] 2017-09-24 18:11
@mikehenrty, I just noticed while looking through the changes for #455: Should we also start using async/await in the backend code? #430 took care of pretty much everything in the frontend, but there's a bunch of promise-based async stuff in the backend as well

**Comment by mikehenrty** [comment] 2017-09-24 19:06
@nevik yeah, would love to start doing this on the backend as well. there's still some promised based stuff in the front-end here and there too I believe.

**Comment by nevik** [comment] 2017-10-02 09:49
@mikehenrty had a go at converting the server code to async/await, but ran into the following problem:

> error TS2529: Duplicate identifier 'Promise'. Compiler reserves name 'Promise' in top level scope of a module containing async functions.

This is caused by the usage/import of `bluebird` Promise, which would conflict with the ES6 Promise that the TS compiler wants to use for async/await.

Is there any particular reason for (keeping on) using `bluebird`? Or could we switch the server code to plain ES6 Promises as well?

**Comment by mikehenrty** [comment] 2017-10-02 13:47
> Is there any particular reason for (keeping on) using bluebird? Or could we switch the server code to plain ES6 Promises as well?

I'm fine with removing `bluebird` now that we are targeting es6.

**Comment by nevik** [comment] 2017-10-02 15:42
Cool. I'll try to get around to this soon. It probably makes sense to remove `bluebird` and switch to async/await in one go.

@kenrick95 if you feel like doing this, and there isn't a PR from me today or tomorrow, go right ahead -- in that I case I probably won't get around to it until next weekend ;)

**Comment by nevik** [comment] 2017-10-14 13:46
Since #491 is now merged, we can use async/await in the server part as well :)

**Comment by mikehenrty** [comment] 2017-10-23 09:40
We are now using async/await in multiple places, and will continue to use it going forward. Let's incrementally switch to this new API when we touch parts of the code rather than doing large refactorings.

With that in mind, I'm closing this bug as we won't have separated work for this.

**Closed by mikehenrty** 2017-10-23 09:40 UTC
