### ISSUE TITLE
Make sure basket_token actually gets saved on account creation

### ISSUE THREAD

**Issue by phirework** [mozilla/voice-web#2357] opened 2019-11-17 03:02 UTC

**Comment by mbransn** [comment] 2019-11-18 19:07
@phirework is this the same as #2330 ? cc @LRSaunders4 to help confirm.

**Comment by rileyjshaw** [comment] 2019-11-19 05:22
Closing this; the issue is tracked well enough by #2330, and I believe it's fixed by https://github.com/mozilla/voice-web/pull/2377.

**Closed by rileyjshaw** 2019-11-19 05:22 UTC
Labels: Priority: P0, UX, voice-challenge
