### ISSUE TITLE
Stats: Top Contributors and Contribution Activity language

### ISSUE THREAD

**Issue by kosciCZ** [mozilla/voice-web#2522] opened 2020-01-07 12:58 UTC
Hi! 

I would like to suggest a change in the User Dashboard interface. I think it would make sense that if I select a language other than "All" in Your languages ("Čeština" in my case), the Top Contributors and Contribution Activity should switch to statistics for that selected language by default, as this is presumably what the user wants to see when they switch to a specific language.

If you think this change is worth accepting, I am willing to help out in implementing it. 

Best Regards,
Jan Koscielniak

**Comment by MichaelKohler** [comment] 2020-02-22 02:41
I'd say this is a duplicate of https://github.com/mozilla/voice-web/issues/1565

**Closed by MichaelKohler** 2020-02-22 02:41 UTC
