### ISSUE TITLE
Add support for foreign languages (e.g. Klingon or R'lyehian)

### ISSUE THREAD

**Issue by tobozo** [mozilla/voice-web#398] opened 2017-08-02 16:31 UTC
The "Your English Accent" field in the profile settings only allows selection of English accents, but there is no such slot for *Klingon English*, *R'lyehian English* or even *French English* (although the is a *Canadian English* choice).

How can I donate my voice if my accent isn't listed, should I select then vocally try to emulate one of the listed accents ?

**Comment by mikehenrty** [comment] 2017-08-03 10:09
Yup, we realize we have a problem with the messaging. We definitely want your voice! We're working on it in #242.

Duplicate of #242.

**Closed by mikehenrty** 2017-08-03 10:09 UTC
