### ISSUE TITLE
verifying on mobile: submit button text gets selected on click (just an annoying bug)

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#856] opened 2018-02-10 08:41 UTC
verifying sentences on Firefox for Android is kinda annoying atm., because pressing yes or no constantly selects the text as if I want to copy it. (for whatever reason; I'm not long-pressing at all)

I would be glad if someone could take a look.

![screenshot_20180210-093536](https://user-images.githubusercontent.com/5685512/36060259-4037ac70-0e46-11e8-9cb1-d832d21768fc.png)

**Comment by Gregoor** [comment] 2018-02-10 12:23
duplicate of #803

**Closed by Gregoor** 2018-02-10 12:23 UTC
