### ISSUE TITLE
Shard of dataset

### ISSUE THREAD

**Issue by Elch123** [mozilla/voice-web#1344] opened 2018-08-12 19:33 UTC
Could you please allow for downloading a fragment (100Mb) of the dataset? The full dataset is large, and I lack space to expand the entire dataset.

**Comment by mikehenrty** [comment] 2018-09-05 15:34
@Elch123 is there a particular fragment you are interested in? or just a representative sample?

**Comment by Elch123** [comment] 2018-09-05 15:37
Just a representive sample, so I can begin work on a machine with an ssd that can't hold the full dataset.

**Comment by Gregoor** [comment] 2019-01-09 13:42
Duplicate of #1206

**Closed by Gregoor** 2019-01-09 13:42 UTC
Labels: Type: Enhancement
