### ISSUE TITLE
Equalise volume of sound clips for review

### ISSUE THREAD

**Issue by NAHarris** [mozilla/voice-web#445] opened 2017-08-31 12:03 UTC
Because of the many different sound sources, the volume levels of different clips varies widely. As a result, some are unexpectedly loud, and others almost too quiet to hear at a normal volume level. 

To avoid this, the volume level of the speech in the clips should be normalized before replay. Because clips can contain clicks and pops, as well as large amounts of near-silence, these should be ignored when setting the output level. This could be implemented by detecting voiced sounds, and using the volume level of those voiced sounds to set the gain.

**Comment by kdavis-mozilla** [comment] 2017-08-31 12:51
It does make it harder to validate when the volume levels vary. However, having the varying volume levels in the audio files is actually useful as any speech recognition engine trained from these files will learn how to deal with varying volume levels.

**Comment by jf99** [comment] 2017-09-01 11:22
Good point @kdavis-mozilla. => So play a normalized version of the audio files for validation, but train your neural networks with unnormalized audio.

**Comment by PaulXiCao** [comment] 2017-09-04 13:24
imo normalizing the volume makes sense for user validation as already mentioned.
There might even be a use case later for training purposes. dont know but even so we can implement it with little work.

I have the following idea of implementation:
* before saving the audio clip to S3 we could normalize it 
* save raw input and normalized clip to cloud
* for user validation: try retrieving the normalized clip
* if availabe: done
** if not 
*** retrieve raw clip
*** normalize
*** play normalized clip to user
*** save normalized clip to cloud

this should limit the work load for the server as normalizing needs power and saving normalized clip only data space.

**Comment by mikehenrty** [comment] 2017-09-27 15:25
Duplicate of #336.

**Closed by mikehenrty** 2017-09-27 15:25 UTC
