### ISSUE TITLE
Mismatch between percent of goal achievement on contribution page vs goals page

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1918] opened 2019-03-28 13:27 UTC
[Preconditions]:
Set a daily goal (e.g. 5 clips for listening only)

[STR]:
1. Open https://voice.allizom.org/en/goals
2. Click the "Listen" button
3. Accomplish your goal by listening 5 clips

[Actual result]:
"You've reached 800% of your daily 5 validation goal"
On https://voice.allizom.org/en/goals - " 100% of daily goal" is displayed

![2019-03-28_14h51_28](https://user-images.githubusercontent.com/41474886/55161348-03972400-516e-11e9-9832-251939675e0d.png)

**Comment by rleitan** [comment] 2019-03-29 13:19
I can still reproduce this issue after I edited my goal several times and click contribute from the navigation bar.

**Comment by Gregoor** [comment] 2019-04-15 07:30
I'm failing at reproducing it 🙈 

Is it happening reliably for you?

**Comment by rleitan** [comment] 2019-04-16 15:34
Yes, I reproduced it with 2 different accounts

**Comment by Gregoor** [comment] 2019-04-18 14:09
Oh I think I misunderstood the issue. We're showing by how much we're overshooting in the success screen but in goals we're capping it at 100%.

@mbransn: Should we make it consistent and also allow overshooting in the goal circle progress? (on the dashboard)

**Comment by mbransn** [comment] 2019-04-23 17:54
No goal overshooting! The submission success screen text should still show Common Voice overall goal progress. When someone completes a person goal they get a banner + an award! :) [See wireframes](https://overflow.io/s/92K0N8/?node=14878542):

<img width="1317" alt="Screen Shot 2019-04-23 at 10 48 23 AM" src="https://user-images.githubusercontent.com/18686986/56604012-db0c1980-65b5-11e9-8868-6bca54e6316a.png">

@Gregoor can we please reuse [our banner UI](https://zpl.io/aXM9Z0j) for this? (remove the 'bug reporting' CTA and center the dismiss `x`)

**Comment by Gregoor** [comment] 2019-04-24 08:41
Oh, it seems like I misread something, don't know how I got the personal goal success progress idea 😕 I reverted that.

As alluded to before I've reused the notification badges, for the award, for now. Do we maybe want to consolidate those UIs? I feel like they serve a similar purpose. So maybe i should use the banner UI for all notifications?

**Comment by rleitan** [comment] 2019-04-24 16:35
This issue is verified as fixed!

**Comment by mbransn** [comment] 2019-04-24 17:05
@Gregoor the issue with the notification toast for now is that it goes away too quickly (for me at least). I'm unable to click on it in time to see my award! I fear this will be the same for others. Sadly it's not a solve to use the banner UI for all notifications because it's meant to be loud and actionable, where as toasts are meant to be quiet and passive. I'll move this to a new issue and we can prioritize as needed.

**Comment by mbransn** [comment] 2019-04-29 16:18
@Gregoor can you review my comment above? Is the banner now static?

**Comment by Gregoor** [comment] 2019-04-29 16:19
that's the same as #1970 right? Static meaning that it doesn't go away unless closed by clicking X or the CTA? Then yes, that's fixed

**Comment by mbransn** [comment] 2019-04-29 17:12
Yes! 🙈 Thanks @Gregoor ❤️

**Closed by mbransn** 2019-04-29 17:12 UTC
Labels: Type: Bug
