### ISSUE TITLE
show unverified hours (on top of verified hours)

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1013] opened 2018-05-21 07:43 UTC
It would be nice if the graph on the front page would also show us the number of unverified recorded hours in the db :)

Or would that discourage people from recording?

**Comment by missuniverse** [comment] 2018-05-21 21:13
@Djfe I think it would rather reduce the disparity between the amount of confirmed recorded hours and the amount of unverified recordings. Good idea!

**Comment by Gregoor** [comment] 2018-05-22 08:56
Maybe for the new home page, @m-branson?

**Comment by m-branson** [comment] 2018-05-22 09:44
@Djfe this is very much a metric we're strategically looking to surface. Still determining which form this will take (graph, number, etc). Agreed that this may help promote and prompt contributors to validate clips (in addition to record clips). Also note that this is an assumption we're looking to validate, test and refine once implemented.

@Gregoor how do you want to track this? Adding a metrics & design label for now.

**Comment by Gregoor** [comment] 2018-05-22 09:51
Thanks, works for me 🙂

**Comment by Djfe** [comment] 2018-12-14 09:44
I think this is fixed now, isn't it?

**Comment by Gregoor** [comment] 2018-12-14 10:08
I don't think it is. The graph still only shows total hours and verified hours (and not yet-to-be-verified hours).

**Comment by mbransn** [comment] 2018-12-14 23:18
@Gregoor I believe we talked about this a bit ago over on Zeplin during new homepage implementation and the UX recommendation was to use a black line/dot to serve as the 'Hours To-Be-Verified' plot on the graph. I say go for it 👍

**Comment by Gregoor** [comment] 2018-12-17 07:35
Oh sorry, I don't recall 🙉 Will look into this one asap.

**Comment by mbransn** [comment] 2020-03-09 23:19
Closing this out -- feedback and research are indicating that actionable metrics such as 'yet-to-be-verified' hours would be better provided as insights on the stats dashboard (once logged in).

**Closed by mbransn** 2020-03-09 23:19 UTC
Labels: Metrics, Type: Enhancement, Type: Investigate
