### ISSUE TITLE
Error in "listen" section (new interface)

### ISSUE THREAD

**Issue by Sav22999** [mozilla/voice-web#1224] opened 2018-07-05 20:09 UTC
It doesn't happen always.
When I review many sentences, I receve this message, and, if I refresh page it doesn't show me nothing.
It happens both Desktop and Mobile (android).

![immagine](https://user-images.githubusercontent.com/32335378/42345524-e4819180-809f-11e8-8457-1087734d4d03.png)
![immagine](https://user-images.githubusercontent.com/32335378/42345552-f556a7ca-809f-11e8-8b24-858cd1d5afc1.png)

This is console 
![immagine](https://user-images.githubusercontent.com/32335378/42345560-fdaa288e-809f-11e8-9fff-a95d5a6bcf39.png)

This is after refresh
![immagine](https://user-images.githubusercontent.com/32335378/42345586-1676395c-80a0-11e8-9121-a755559c310a.png)

I think it happens when sentences which I can review are finished

**Comment by mikehenrty** [comment] 2018-07-06 09:07
duplicate of #989

**Closed by mikehenrty** 2018-07-06 09:07 UTC
