### ISSUE TITLE
Use shtooka.net

### ISSUE THREAD

**Issue by rugk** [mozilla/voice-web#347] opened 2017-07-24 11:44 UTC
Maybe you can use http://shtooka.net/ as another source.

**Comment by mikehenrty** [comment] 2017-07-24 19:41
Duplicate of #23.

**Closed by mikehenrty** 2017-07-24 19:41 UTC

**Comment by rugk** [comment] 2017-07-24 20:44
No, that does not provide texts, but actually finished sound/text (i.e. word) correlations. And it seems to use a free license.
