### ISSUE TITLE
Getting the same recording multiple times for validation

### ISSUE THREAD

**Issue by a3nm** [mozilla/voice-web#260] opened 2017-07-01 20:54 UTC
On https://voice.mozilla.org/, "Help us validate sentences", I got the same recording three times in quick succession. I don't think it makes sense to ask the same user to validate the same recording more than once?

This may be related to #255

**Comment by Phrozyn** [comment] 2017-07-02 22:10
Yes. I too am seeing this behavior. Single reader, same sentences (about a handfull of different ones but always seem to repeat)  all seem to be the same reader, although I've submitted readings myself.

**Comment by Omniscimus** [comment] 2017-07-03 14:11
Duplicate of #241 @kdavis-mozilla

**Comment by a3nm** [comment] 2017-07-03 15:17
It's related but not a duplicate: this bug is about getting recordings for validation multiple times, but #241 is about getting the same sentence for recording multiple times.

**Comment by orschiro** [comment] 2017-07-15 05:09
This is just stupid and needs to be resolved quickly. It's really unmotivating if you want to contribute by approving submissions and every time you return to the page, you always get to hear the same submission.

**Comment by joshua-montgomery** [comment] 2017-07-16 03:02
I am currently getting "Null" - no recordings for validation.

**Comment by lopis** [comment] 2017-07-17 09:16
@orschiro I don't want to sound rude but did you consider contributing a fix? Software always has bugs. Calling it stupid really doesn't help the project.

**Comment by orschiro** [comment] 2017-07-17 11:03
@lopis, I apologise. I didn't want to sound rude. It just felt very frustrating in that moment for me as a user because I really want to contribute to the project by validating and recording. 

I don't have the software skills to contribute a fix to this bug.

**Comment by lopis** [comment] 2017-07-17 11:21
@orschiro I know you want to help; you and each one of us. But it helps to remember that it's only humans working on the other side. I also don't have the time to give more meaningful help to the project so I'll patiently wait :)

**Comment by orschiro** [comment] 2017-07-17 11:22
To help the project financially, what's the best place to donate? Mozilla directly?

**Comment by mikehenrty** [comment] 2017-07-17 12:23
Hi all, thanks for your interest in this bug.

We actually have a fix for this right now, but all weekend there have been thousands of active users (due to a campaign we ran in Firefox). We are waiting for this traffic to die down before deploying this fix.

Stay tuned!

**Comment by mikehenrty** [comment] 2017-07-17 12:25
> To help the project financially, what's the best place to donate? Mozilla directly?

We are not set up to take financial donations for Common Voice project. For now, reading sentences (and soon as we fix this, listening to sentences) is the best way to contribute directly to this project.

But you can always, of course, contribute money to the Mozilla project.
https://donate.mozilla.org/en-US/

**Comment by mikehenrty** [comment] 2017-07-17 17:23
This is now fixed in production. I gave it a try and it seems to be much better at randomization. That said, if this problem re-surfaces, please re-open this bug (or file a new one if you don't have access).

**Closed by mikehenrty** 2017-07-17 17:23 UTC
Labels: Priority: P1, Triage

**Comment by a3nm** [comment] 2017-07-18 13:57
I agree, I am now getting lots of different sentences, so this looks fixed to me. Thanks!
