### ISSUE TITLE
Guidelines: which speeches should be considered ok? (quality-wise)

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#857] opened 2018-02-10 08:57 UTC
Should there be guidelines for recording your voice/verifying speech?

I encounter speech every now and then where the speaker misspoke a word and corrected him/herself during the recording by repeating a word or so (and uhm).
Now I'm wondering, should I re-record, when this happens. Should as the verifier vote with no?

Some guidelines certainly would be nice.
I could definitely see that correcting yourself could be part of symantics instead of syntax, so that the translation algorithm shouldn't correct for these issues.

If the discourse is a better place for this, then don't hesitate to tell me so.
But maybe some guidelines already exist and I missed them?

Regards

**Comment by Djfe** [comment] 2018-02-10 09:45
I've also been wondering how important correct intonation is:
Question vs exclamation and so on

**Comment by Gregoor** [comment] 2018-02-10 12:29
duplicate of #273 

Thanks for re-rasing that, I agree that this is something we should think about and show more clearly to users.

**Closed by Gregoor** 2018-02-10 12:29 UTC
