### ISSUE TITLE
Adding other languages

### ISSUE THREAD

**Issue by wathek** [mozilla/voice-web#401] opened 2017-08-03 13:56 UTC
Hi, I wanted to know how can we help to add more languages recording?
Do we need to translate the text to the needed language and then ask people to record their voice?
Do we need to have another text set for each language?

This is really a good project and I'm very interested in contributing to this.

**Comment by mikehenrty** [comment] 2017-08-04 08:58
Hi @wathek, thanks for your report. We are definitely interested in translating to other languages. You are correct in that we would need to translate the text of the website into this new language, and then find public domain sentences for people to read. We have a goal of adding a second language before the end of the year.

I think a big factor in us choosing a second language will be finding enough public domain text for people to read. If you know of any good sources, please let us know in #213.

Duplicate of #213.

**Closed by mikehenrty** 2017-08-04 08:58 UTC
