### ISSUE TITLE
Additional instructional prompts needed in Speak

### ISSUE THREAD

**Issue by tiffanystallings** [mozilla/voice-web#362] opened 2017-07-26 15:39 UTC
Just a small suggestion. "Press again to stop recording" and the ability to playback the recording immediately and re-record if necessary before hitting a "Next" button could be nice.

It's obviously possible to figure it out without additional prompts, but I'd like to think I'm not the only one who was unsure what was happening or if I was doing it right until I had recorded all three sentences.

**Comment by jdittrich** [comment] 2017-07-26 20:38
related: #313

**Comment by mikehenrty** [comment] 2017-07-27 00:10
Yeah, let's see if I can address you concerns with #313. If not, we can re-open this.

Duplicate of #313.

**Comment by mikehenrty** [comment] 2017-07-27 00:11
Oh, and thank you for the report, @tiffanystallings !!

**Closed by mikehenrty** 2017-07-27 00:10 UTC
