### ISSUE TITLE
Make it impossible to validate a sentence without having listened to it first

### ISSUE THREAD

**Issue by a3nm** [mozilla/voice-web#280] opened 2017-07-18 13:37 UTC
I misclicked on the "Yes!" button to validate a sentence before I had listened to it, and apparently the system took this into account. I think it would be better if the system didn't allow the validator to click "Yes!" or "Nope." before having listened to the sentence to be validated.

**Comment by mikehenrty** [comment] 2017-07-19 09:06
Duplicate of #212.

**Closed by mikehenrty** 2017-07-19 09:06 UTC

**Comment by a3nm** [comment] 2017-07-19 09:10
OK, sorry for the duplicate and thanks for closing.

**Comment by mikehenrty** [comment] 2017-07-19 09:15
No problem! Duplicates are like votes for the original bug, so it's useful. Thanks for all your contributions @a3nm !!
