### ISSUE TITLE
[Staging] Click on share button has no effect

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1063] opened 2018-06-06 14:24 UTC
Clicking Share button after recording a sentence has no effect.

![share](https://user-images.githubusercontent.com/5293100/41044185-526cd6f4-69ae-11e8-8929-83f3cf83e158.png)

**Comment by mikehenrty** [comment] 2018-06-06 16:52
dupe of #1055

**Closed** 2018-06-06 16:52 UTC
Labels: Type: Bug
