### ISSUE TITLE
new answer flag when listening: "technical issues"

### ISSUE THREAD

**Issue by HuBandiT** [mozilla/voice-web#327] opened 2017-07-23 02:05 UTC
This is a suggestion to add a "technical issues" flag when listening and answering.

The first sentence I received when trying to help with listening was from a mic that was too hot - the speaker spoke the required sentence with good pronunciation, however about 30% of the recording was clipping/distorting beyond recognition. Without the original sentence displayed in its entirety, I would have had to guess what was being said - consequently I do not think this is good training data for a machine.

I would like us to be able to mark such recordings upfront, so that it is possible to exclude them from the learning process.

**Comment by Omniscimus** [comment] 2017-07-23 07:01
Maybe this should just be marked 'Nope'. It's not super useful for the system to have a bucket of recordings marked as 'too bad mic', it's just not usable.

**Comment by rugk** [comment] 2017-07-23 12:55
Well… maybe the system could then filter all recordings in this sequence as they might all suffer from the bad technical issue…

**Comment by mikehenrty** [comment] 2017-07-23 15:19
@kdavis-mozilla is clipping bad? is it worthwhile to try and train an engine to understand clipping speech?

**Comment by kdavis-mozilla** [comment] 2017-07-24 07:55
@mikehenrty Clipping is definitely bad. However, as we're seeing it in the wild, solving the problem will also be hard, as we want the system to work in the wild, which means work with some clipping.

Ideally a system would learn how do understand clipped speech. However, as information is destroyed during clipping, this is in general impossible. But, if the audio is clipped only "a bit," it's understandable by a human, then, in theory, it should be able to be understood by a machine.

The question, as always in these things, comes down to how much clipping is OK. @HuBandiT had a interesting comment in this regard

_Without the original sentence displayed in its entirety, I would have had to guess what was being said.._

So this means that the interpretation of the audio is biased through our presentation of the text. Not good. Further, @HuBandiT  went on

_...consequently I do not think this is good training data for a machine._

which I think I agree with in this case.

But in general if a human can understand it, it's useful data. However, due to the above bias, it might be hard to determine exactly where the "human understandable line" is with our current approach.

This exposes a difficult problem.

**Comment by rugk** [comment] 2017-07-24 08:26
I thin a rule of thumb could be: "When you can write down the text exactly as given by only listening to the sentence, then click 'Yes', otherwise 'No'."
This automatically let's the user click on "Yes" for quite, but correct sentences and "No" for sentences where words etc. are missing.

**Comment by Omniscimus** [comment] 2017-07-24 08:42
> I think a rule of thumb could be: "When you can write down the text exactly as given by only listening to the sentence, then click 'Yes', otherwise 'No'."

But sometimes someone has such a heavy accent that I'm confused about what exactly the person was saying, even though they it was perfectly understandable by someone familiar with that accent. I'd need the sentence to verify it.

How about: "When you can confirm that the recording matches the sentence word-for-word, click 'Yes!'; otherwise click 'Nope.'"

Plus (a link to) some extra information (in the FAQ?) like "For example, if the recording is very soft but you can verify it with the volume turned up, click 'Yes!'. If the recording is too distorted to be able to hear certain words, click 'Nope.'. If the recording omitted some words from the sentence, words were added or the order of the words was changed, click 'Nope.' If the reader has a strange accent but you can otherwise verify that they read the sentence correctly, click 'Yes!'."

**Comment by mikehenrty** [comment] 2017-07-25 11:18
Ok, sounds like we can handle this one in #273.

Duplicate of #273.

**Closed by mikehenrty** 2017-07-25 11:18 UTC
Labels: Triage
