### ISSUE TITLE
Don’t show email login in iOS app

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1882] opened 2019-03-06 15:35 UTC
It’s not possible to login with your email in the iOS app so it’s confusing to present it as an option. The site should just list Firefox/Github/Google when it detects the visitor is using the iOS app.

**Comment by Gregoor** [comment] 2019-03-06 15:41
Duplicate of #1649 

I know you're asking for something a bit different, but let's track it over there.

**Closed by Gregoor** 2019-03-06 15:41 UTC
