### ISSUE TITLE
Adding `first=1` to the challenge dashboard crashes it

### ISSUE THREAD

**Issue by rileyjshaw** [mozilla/voice-web#2346] opened 2019-11-15 16:13 UTC
Test plan:

- Navigate to https://voice.allizom.org/en/dashboard/challenge

Challenge dashboard should load correctly.

- Switch the URL to https://voice.allizom.org/en/dashboard/challenge?first=1

Challenge dashboard crashes.

**Comment by phirework** [comment] 2019-11-15 18:41
Pretty sure this is fixed after the last round of changes - or at least, can no longer replicate.

**Comment by rileyjshaw** [comment] 2019-11-15 19:10
I'm still seeing this! I can look into it on my end if you can't repro.

**Comment by mbransn** [comment] 2019-11-15 19:24
+1 reproducible on my end as well.

**Comment by mbransn** [comment] 2019-11-15 19:27
I wonder if this is indeed P0? While important that things not crash, it's most important that the onboarding modal trigger accurately during the flow (which we have confirmed as part of #2348) not when URL switched manually.

**Comment by phirework** [comment] 2019-11-15 19:30
What the heck, I can't reproduce this locally OR on staging. 

https://www.dropbox.com/s/5jxmpbqd2mfp217/Screen%20Recording%202019-11-15%20at%2014.27.42.mov?dl=0

**Comment by ragnarokatz** [comment] 2019-11-15 19:36
even https://voice.allizom.org/en/dashboard/challenge crashes for me.

**Comment by phirework** [comment] 2019-11-15 19:39
Agree with @mbransn on this not being P0 though. 

@ragnarokatz are you enrolled in a challenge?

**Comment by ragnarokatz** [comment] 2019-11-15 19:42
@phirework I don't think so. nor can I find the correct navigation path to enroll in one.

**Comment by phirework** [comment] 2019-11-15 19:46
@ragnarokatz These are new features we're testing out through a partnership pilot project first, so there's no path to discovery just yet. We'll be sharing an actual invite link once it's live. For now, you can test on staging with this link: https://voice.allizom.org/?challenge=pilot&team=mozilla

**Comment by mbransn** [comment] 2019-11-15 19:53
@phirework confirmed fixed on my end; multiple tests. Works when triggering the link once logged in.

**Comment by ragnarokatz** [comment] 2019-11-15 19:54
@phirework thanks!

**Comment by rileyjshaw** [comment] 2019-11-15 20:04
Good point on the priority level. Updating to P1!

**Comment by rileyjshaw** [comment] 2019-11-15 20:09
(Also: this may be fixed. Can anyone still repro?)

**Comment by mbransn** [comment] 2019-11-15 20:11
Confirmed fixed on my end still.

**Closed** 2019-11-15 20:43 UTC
Labels: Priority: P1, voice-challenge

**Comment by rleitan** [comment] 2019-11-18 14:49
I can reproduce it if I am not logged in and I go directly to https://voice.allizom.org/en/dashboard/challenge?first=1.
First, "An error occurred" message is displayed, the page is redirected to login screen

**Comment by phirework** [comment] 2019-11-18 15:01
If you're not logged in, going to `dashboard` *should* redirect you to login because that's an internal screen. That's expected behaviour. The error message flashing isn't ideal but also not a huge problem.

**Comment by rleitan** [comment] 2019-11-18 15:07
I would reopen the issue as enhancement with low priority. @mbransn
