### ISSUE TITLE
Stats overwrite each other if multiple windows are open

### ISSUE THREAD

**Issue by iangilfillan** [mozilla/voice-web#798] opened 2018-01-08 15:37 UTC
If more than one window is open, the validate and contribute stats overwrite each other. For example:
1) Open two windows (10 contributions, 10 validations)
2) Record 5 validations in window 1 (15 c, 10v)
3) Record 5 contributions in window 2 (10c, 15v)
4) Reloading the stats from window 1 are lost.

Tested on Ubuntu 14.04, Firefox 57.0.3 (64-bit),

**Comment by Gregoor** [comment] 2018-01-15 09:59
Thanks for raising that shortcoming. I was about to mark it as a duplicate of #392, but there's a simpler way for us to solve it across browser tabs without having to solve the technical and legal challenges of syncing profiles across browsers.
We just have to listen to the [storage event](https://developer.mozilla.org/en-US/docs/Web/Events/storage) and update the site accordingly.

**Closed** 2018-01-15 16:33 UTC
Labels: Type: Bug, Type: Enhancement
