### ISSUE TITLE
previously recorded prompts reappearing for recording

### ISSUE THREAD

**Issue by DewiBrynJones** [mozilla/voice-web#1067] opened 2018-06-06 17:28 UTC
Spotted in Welsh CommonVoice - prompts that have already been recorded are re-appearing for the user to record again. 

The cause is an inconsistancy between encoding and decoding of sentences. 

Client side : 
 
https://github.com/mozilla/voice-web/blob/7a322ed51a15af2bc0bbcfa540f769c96ff45c5a/web/src/services/api.ts#L126
       
But server side:
https://github.com/mozilla/voice-web/blob/7a322ed51a15af2bc0bbcfa540f769c96ff45c5a/server/src/lib/clip.ts#L90

Server should use `decodeUriComponent`

This bug doesn't surface when there are a large collection of sentences as in English. But will for new languages with initially smaller corpus of sentences.

**Comment by Gregoor** [comment] 2018-06-06 17:41
Thanks for deep diving into that, I just pushed a commit to use decodeURIComponent instead.
Though my intuition is that this might be related to the three instance running Common Voice having their own separate cache, hence sometimes serving sentences based on outdated information on which are already used. I decreased the cache size to 100 for now.
Longer-term I want to throw out these caches completely and instead cache at the DB level itself.

**Comment by Djfe** [comment] 2018-06-08 02:30
I'm noticing this as well in German.
The chance something like 1 in 10 strings that is repeated, probably higher. (very noticeable)

**Comment by Djfe** [comment] 2018-06-08 03:09
I got one sentence 3 or 4 times now, I think.

**Comment by Djfe** [comment] 2018-06-08 03:14
5? :D 
wtf, German has 5000 sentences

**Comment by Djfe** [comment] 2018-06-08 03:15
![screenshot](https://i.imgur.com/r9cZpMd.png)
The last I had both upwards of 2 times now...

**Comment by Djfe** [comment] 2018-06-08 03:17
the next one was also not new
so three sentences after each other: a repetition

**Comment by jf99** [comment] 2018-06-08 11:42
I can confirm. This also happens in German.

**Comment by Gregoor** [comment] 2018-06-08 15:32
Thanks for your reports, I'm working on getting a replacement for our faulty cache in now. Will update this once done!

**Comment by Gregoor** [comment] 2018-06-08 17:45
Alrighty, we moved to DB-caching, so this problem should be solved (at least I couldn't recreate it anymore with my ~20 recordings & ~50 validations just now). Please let me know if not, I very much appreciate it 🙂

**Comment by mikehenrty** [comment] 2018-06-28 10:56
Let's close this for now since I think it's solved. But we will file a new one if it comes back.

**Closed by mikehenrty** 2018-06-28 10:56 UTC
