### ISSUE TITLE
Allow 'other' or multiple for "your english accent"?

### ISSUE THREAD

**Issue by edunham** [mozilla/voice-web#296] opened 2017-07-19 16:34 UTC
I speak US English with a noticeable NZ accent. In NZ, people think I have a strong American accent. In the US, people always ask me where I'm from. The demographics dropdown allows me to only select one region, and no "other". Since locals in both countries assume I'm from the other, it seems disingenuous and like it might reduce the quality of your data to claim to have solely either accent. 

Please consider doing one of:

1) Document what someone in my situation, with a mixed accent, should put in that box, or
2) Allow multiple regions of accent to be selected, or
3) Add 'other'

depending on what your goals are for using that metadata.

**Comment by edunham** [comment] 2017-07-19 16:40
This has a lot of overlap with  https://github.com/mozilla/voice-web/issues/242 but I'll let contributors decide whether it should be closed, since I'm requesting a specific change and I'm not sure how actionable #242 is in its current form

**Comment by mikehenrty** [comment] 2017-07-27 23:13
What we did was add a "Non-Native" option to our drop down list in #242. Talking to our speech team, this is the best way forward here. Thanks for the report!

Duplicate of #242.

**Closed by mikehenrty** 2017-07-27 23:13 UTC

**Comment by edunham** [comment] 2017-07-28 21:56
OK... That doesn't really solve my problem, since I'm a native English speaker with a split accent. Which do you recommend I enter myself as?

**Comment by nukeador** [comment] 2019-05-14 20:26
Hello,

We have opened a call for feedback about Common Voice's languages and accents strategy. I would like to invite you all to the conversation and add your input before May 26th.

Thanks so much for your feedback!

https://discourse.mozilla.org/t/feedback-needed-languages-and-accents-strategy/40352
