### ISSUE TITLE
Recordings are cut off

### ISSUE THREAD

**Issue by 12people** [mozilla/voice-web#346] opened 2017-07-24 08:17 UTC
In listening, I've happened upon recordings that are great except cut off, ending too soon.
In recording, I've also noticed that some of my recordings were cut off.

**Comment by mikehenrty** [comment] 2017-07-24 19:31
Yikes, when did you notice _your_ recordings were cut off? On the `submit` page?

**Comment by 12people** [comment] 2017-07-24 19:39
Yes, on the submit page. It's probably that I'm clicking the stop button too soon without realizing it. Would be good to check if it's not being cut off a little by software, though, and perhaps to record quarter of a second longer after stop is clicked.

**Comment by MichaelNMaggs** [comment] 2017-07-25 15:59
There are indeed quite a lot of these.  As the final word is incomplete, I am marking them all as "Nope"

**Comment by mikehenrty** [comment] 2017-10-23 09:34
From a code perspective, there is not much we can do to prevent users from ending their recording early.

However, we do want to explain clearly to users that if a recording is cut off, it should be validated as "Nope".

With that in mind, I'm going to mark this on a duplicate of the bug for properly explaining validation criteria.

Duplicate of #273.

**Closed by mikehenrty** 2017-10-23 09:34 UTC

**Comment by iveskins** [comment] 2017-10-26 00:48
What would be the effect of putting a bit of delay on the stopRecording function in the onRecordClick function?
