### ISSUE TITLE
In the new interface "Listen" is blank when you've listened to all the clips

### ISSUE THREAD

**Issue by ftyers** [mozilla/voice-web#1199] opened 2018-07-02 02:33 UTC
It could be a bit confusing for the user. Perhaps a short message like "You've listened to everything we've got, how about making some more recordings?" (Or something with a bit better copy).

![captura de 2018-07-02 04-32-04](https://user-images.githubusercontent.com/449545/42142685-14d0887e-7db1-11e8-82c2-129a887c09ec.png)

**Comment by mikehenrty** [comment] 2018-07-02 10:22
duplicate of #989.

**Closed by mikehenrty** 2018-07-02 10:22 UTC
