### ISSUE TITLE
Sharing profile between browsers?

### ISSUE THREAD

**Issue by woj-tek** [mozilla/voice-web#804] opened 2018-01-14 09:34 UTC
Hi,
thanks for a great project. I'm recording voice and verifying recordings but... I noticed that it seems that profile is tied to browser/maintained by cookies? (different count of recordings/verifications).
Would it be possible to use same profile across browsers? Maybe after creating the profile e-mail the link with UUID and then after opening it a correct cookie would be saved?

**Comment by Gregoor** [comment] 2018-01-15 10:02
Duplicate of #392 

Hi, thank you for the kind words. It is indeed only saved locally inside of localStorage (similar to cookies, but not quite the same). We'd like to support keeping your profile across browser sessions, but there's some technical and legal challenges we have to solve first.

**Closed by Gregoor** 2018-01-15 10:02 UTC

**Comment by woj-tek** [comment] 2018-01-15 11:06
Thanks for pointing me to the correct issue - added my thumbsup there.
