### ISSUE TITLE
Languages page issue - subscription dialogue

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#984] opened 2018-05-06 18:54 UTC
something is off here 😅
the German one is english
![screenshot_20180506-204905](https://user-images.githubusercontent.com/5685512/39676686-295d67f8-516f-11e8-8b90-88dd0fa1d488.png)
The French, Portuguese and some other ones are German.
![screenshot_20180506-204932](https://user-images.githubusercontent.com/5685512/39676688-2e90dcfa-516f-11e8-9e5d-ef9b30e75210.png)
Chinese seems to be correct though
![screenshot_20180506-204938](https://user-images.githubusercontent.com/5685512/39676689-33034930-516f-11e8-8f0a-d5c1263d5781.png)

this is all on the German version of the page

**Comment by Djfe** [comment] 2018-05-07 09:10
The dialogue behind the "get involved"/"Mitmachen" button on the main page, uses the correct language for each dialogue unlike the dialogue on the language page.
This bug is present on allizom.org and mozilla.org

for example german:
![screenshot](https://i.imgur.com/XIs0zgq.png)

**Comment by Gregoor** [comment] 2018-05-07 11:57
Thanks for reporting this! I just the overall wrong-language fixed by not re-using the messages generator.

The language name is a bit more tricky. Currently all the text inside of that modal comes from the `cross-locale.ftl` file, while all the other text on the site comes from the `messages.ftl` file. And the language native names are in the latter file. Now the problem is that we don't have a way to reuse/import single translations across those files. Happy to get input on how one could best solve that.

**Comment by Djfe** [comment] 2018-05-08 01:16
I wouldn't even want that, I just realized what the issue was...
![screenshot](https://i.imgur.com/ZXXIenc.png)

some variable were missing the $
```{lang}```
instead of
```{$lang}```

in the german translations.

I you found another bug then I'm not even sure which one it is hehe.

**Comment by Djfe** [comment] 2018-05-08 01:17
Is there a way to use some checks on Pontoon to enforce, that variables from the source string have to be present in translations?

**Comment by Gregoor** [comment] 2018-07-09 14:13
Thanks for raising this, looks good to me for now.

**Closed by Gregoor** 2018-07-09 14:13 UTC
