### ISSUE TITLE
No error message displayed for invalid email

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#2068] opened 2019-06-12 12:11 UTC
[STR]:
1.Open https://voice.allizom.org/en/datasets
2.Click Enter email to download
3. Enter an invalid email (e.g test )
4.Check the 2 checkboxes

[Expected result]:
Email field should be highlighted with red colour and a descriptive message should be displayed on hover

[Actual result]:
The download button is not clickable and no error message is displayed

[Note]:
The issue is reproducible on prod too

**Comment by MichaelKohler** [comment] 2020-02-22 01:59
Duplicate of https://github.com/mozilla/voice-web/issues/1788

**Closed by MichaelKohler** 2020-02-22 01:59 UTC
Labels: Type: Bug
