### ISSUE TITLE
listening to the same sample twice

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#344] opened 2017-07-24 04:50 UTC
It happened to me a few times already that the website presented me the same voice sample twice.
(same person too, not just the same sentence)

You probably should avoid that from happening ;)

EDIT:
it's happening pretty often

**Comment by Omniscimus** [comment] 2017-07-24 07:23
Duplicate of #241 :smile:

**Comment by mikehenrty** [comment] 2017-07-24 12:43
Need to figure out why this is happening again.

**Comment by ruyfel** [comment] 2017-07-24 12:55
Same problem here, it is always the same person who sounds like a professional narrator.

**Comment by Djfe** [comment] 2017-07-24 20:33
@ruyfel exactly :D

**Comment by ogrisel** [comment] 2017-07-25 07:00
Same problem: this morning (CEST) the validating interface seems to randomly select among only 3 different sentences all from the same speaker.

**Comment by mikehenrty** [comment] 2017-07-25 12:01
Alright everyone. I have some fixes in production that should make this bettter. Are you still seeing it?

**Comment by ajaydee** [comment] 2017-07-25 13:48
It seems to have improved.

**Comment by jf99** [comment] 2017-07-25 15:12
It has certainly improved, but it's still far from perfect. The "professional narrator"* is still very present. Also, almost all of the sentences seem to come from that desert story. I can't remember these sentences showing up when recording my own voice. This story was probably the first set of sentences. Could it be that we can only verify sentences that have been recorded in the first days of the project?

*That's the one who always says things like:
The boy was surprised.
"I'm a women of the desert", she said, averting her face.

**Comment by MichaelNMaggs** [comment] 2017-07-25 16:36
Still happening as at 1635 GMT, 25 August. Several times during the validation of about 50 sentences.

**Comment by ogrisel** [comment] 2017-07-26 16:39
I now get the following instead:

![image](https://user-images.githubusercontent.com/89061/28632716-c04157c4-7231-11e7-933d-44473e7b533d.png)

**Comment by Omniscimus** [comment] 2017-07-26 16:41
@ogrisel see #359

**Comment by ogrisel** [comment] 2017-07-26 16:44
@Omniscimus indeed. When I reload the page. I either get the "Sorry!" message or a new sample that I had never heard in the past. The problem reported originally on this issue seems to be fixed for me.

**Comment by jf99** [comment] 2017-07-26 21:00
I just verified over 400 recordings and had not a single repetition. So yeah, this seems to be fixed.

**Comment by mikehenrty** [comment] 2017-07-26 23:57
Wow, you are a star @jf99 !!!!

As you all may have noticed. We have been having some site stability issues over the last day or two. I think we are finally working through those, and so problems like this *hopefully* are going away. Thanks for your patience!

**Closed by mikehenrty** 2017-07-26 23:57 UTC
Labels: Priority: P1
