### ISSUE TITLE
Mine audio from Wikimedia Commons audio

### ISSUE THREAD

**Issue by picsi** [mozilla/voice-web#302] opened 2017-07-19 23:22 UTC
Is this feasible/desirable? I'm immediately thinking of [LibriVox](http://librivox.org/), which has public domain audiobooks, and Wikimedia Commons, with a treasure trove of spoken, recorded audio: https://commons.wikimedia.org/wiki/Category:Audio_files_by_language

**Comment by kdavis-mozilla** [comment] 2017-07-20 07:12
All good ideas!

In terms of training our speech-to-text engine[[1](https://github.com/mozilla/DeepSpeech)] we are already using [LibriVox](http://www.openslr.org/12/) and [TED](http://www-lium.univ-lemans.fr/en/content/ted-lium-corpus). 

We are _not_, however, using Wikimedia Commons audio[[2](https://commons.wikimedia.org/wiki/Category:Audio_files_by_language)] as in its current form it would require lots of pre-processing which, given the size of our team, we don't have the resources to do.

**Comment by mikehenrty** [comment] 2017-07-20 10:26
Thanks for the suggestions @picsi! Let's change this bug to be about incorporating Wikimedia Commons audio into our published dataset. If you have an further ideas of data sources, we can file a new bug.

**Comment by picsi** [comment] 2017-07-20 12:12
>We are not, however, using Wikimedia Commons audio[2] as in its current form it would require lots of pre-processing which, given the size of our team, we don't have the resources to do.

Perhaps there could be a way of crowsourcing that effort 🤔

**Comment by mikehenrty** [comment] 2017-07-20 12:17
> Perhaps there could be a way of crowsourcing that effort 🤔

Yes, please help us brainstorm this! :) we are still a very small team, and most of our efforts have been around keeping the site from falling over the last few days.

Here's a place to have those kind of discussions: 
https://discourse.mozilla-community.org/c/voice

**Comment by kdavis-mozilla** [comment] 2017-07-20 12:18
@picsi Possibly

Basically the problem is the audio is not segmented. In other words, there are not timestamps associated with where each sentence or phrase starts and stops. These well defined audio segments containing a single sentence or phrase are required to train a speech-to-text engine.

**Comment by picsi** [comment] 2017-07-20 23:22
Thanks for the encouragement, @mikehenrty!

@kdavis-mozilla There are plenty of one-word audio soundbites, such as the ones here:

https://commons.wikimedia.org/wiki/Category:English_pronunciation

**Comment by birbilis** [comment] 2017-07-21 10:27
doesn't there exist software to detect gaps and add timing info? YouTube has such functionality for videos from what I remember

**Comment by est31** [comment] 2017-07-21 13:17
There seems to be https://github.com/lowerquality/gentle . It seems one has to implement the actual chunking based on that, but its a good step into the direction.

(source: @braindead 's [comment](https://github.com/mozilla/DeepSpeech/issues/722#issuecomment-315720293) in the deepspeech repo)

**Comment by birbilis** [comment] 2017-07-21 14:59
quoting from:
https://lowerquality.com/gentle/

it seems that it is English only, but could be a start - has some test button on the above URL

> There are three ways to use Gentle: 
> * through the graphical user interface in a web browser, which allows uploading media and transcript, and then downloading the results as JSON, CSV, or a portable Zip archive; 
> * by making programmatic HTTP requests—the /transcriptions endpoint accepts an async=false query argument, which leaves the connection open until alignment completes, and then immediately returns the alignment in JSON format; and 
> * as a python library. 
>
>Technique: We construct a language model composed of all bigrams within the provided transcript, and combine it with an acoustic model (trained by Kaldi developers on the Fisher English corpus). After running online transcription, we use sequence alignment algorithms to match the result with the original transcript.

**Comment by birbilis** [comment] 2017-07-21 15:10
One could probably use Speech to Text to produce audio from the text, then compare the real audio with the produced one using filtering (for voice frequency range) and then feature tracking (like it is done for video frames or at least the concept) to sync the two audio curves. 

After that, since the TTS curve can be annotated with positions in the text (the TTS engine can do that I believe by sending feedback as it produces the synthetic speech), and one has a mapping between TTS audio curve and (filtered) spoken audio, they can align the spoken audio with the text source

For phrase gaps though, simpler methods could be used, just filter maybe in voice frequency range, then find gaps at a silence threshold and then statistically or with other method try to remove the gaps from other pauses that are not end of a phrase, by getting timings from a TTS engine and adjusting those on the fly as the text progresses (in case the TTS engine doesn't fall behind or go faster). Aka the TTS engine gives hints where end-of-phrase gaps maybe so that other gaps are ignored

**Comment by monopatis** [comment] 2017-08-06 04:14
Maybe you can use data from an older similar project http://www.voxforge.org/

**Comment by individual-it** [comment] 2017-08-08 06:13
What about using the bible as source? There are a lot of audio versions around e.g.: http://www.audiotreasure.com/

**Comment by picsi** [comment] 2017-08-08 10:26
@individual-it Are those freely licensed? It looks like they're just gratis.

**Comment by nonthewiser** [comment] 2017-08-08 11:14
How about this?
http://www.manythings.org/audio/sentences/

**Comment by individual-it** [comment] 2017-08-08 13:38
> Are those freely licensed? It looks like they're just gratis.

not many information about the license, I've wrote an email asking.
But here are bible resources that claim to be public domain:
http://ebible.org/webaudio/
http://soundbible.com/audio-bible-online.php

**Comment by mikehenrty** [comment] 2017-08-10 12:58
Thanks everyone! Yeah, we have to be very careful about licensing. Not only do we need Public Domain, but we need CC-0, which is the most permissive license possible. Even public domain CC-3 for instance wouldn't work for our current terms. But please keep posting your ideas, as helping us surface content sources is extremely helpful!

http://www.manythings.org/copyright.html

**Comment by Riotism** [comment] 2017-08-13 17:50
A good source on Wikimedia Commons might be https://commons.wikimedia.org/wiki/Category:Files_with_closed_captioning_in_English. This category contains many US Federal Government videos (meaning that they are PD) with closed captions.

**Comment by strob** [comment] 2017-12-02 11:42
Hi! I'm the author of Gentle. Happy to help with scripts, integrations, questions, and issues you might run into.
Unfortunately, Gentle is English-only at the moment.

**Comment by akreal** [comment] 2018-02-13 21:34
There is a corpus based on Spoken Wikipedia:
https://nats.gitlab.io/swc/

**Comment by MichaelNMaggs** [comment] 2018-02-23 23:12
Many of the files on Wikimedia Commons, and all of the text on Wikipedia, can’t be used due to licensing issues. This project needs public domain or CC-0, whereas Wikipedia and much of the content on Commons is under free licences that require attribution. LibriVox works, as that’s all PD, but that’s covered by a separate GitHub issue.

**Comment by birbilis** [comment] 2018-02-25 03:57
Attribution isn't passed on I think if you made something of totally different form based on an Attribution-ShareAlike item. You'd just attribute it once, your users wouldn't need to attribute it again. Could get legal opinion of course on that

**Comment by MichaelNMaggs** [comment] 2018-02-26 16:31
No, that's not correct. The Creative Commons attribution share-alike licences, as used for most of the files on Wikimedia Commons and all of the text on Wikipedia, require attribution by *all* levels of re-user - not only those who make direct use of the original text, but also those who make use of the re-uses of others. That's the 'share-alike' requirement of the licences, and is why much of the material would be legally complex to include in the Common Voice corpus.

**Comment by mikehenrty** [comment] 2018-02-27 01:19
Thanks for clearing that up @MichaelNMaggs. Really great to have your expertise here. I think we can close this for now. But we'll keep an eye out for other sources (especially if we have someone like @strob to help us with the aligment :D ).

**Closed by mikehenrty** 2018-02-27 01:19 UTC
