### ISSUE TITLE
Contribution counters from Challenges page are reset in the 2nd week of challenge 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2366] opened 2019-11-18 10:55 UTC
**STR:**

1. Login to an account signed up to the challenge, who has made some contributions
2. Navigate to Challenges page => Number of recordings and validation are displayed (<0)
3. Click Listen button
4. Validate a sentence
5. Click Back button

**Expected:**
User is redirected to Challenges page, counter for Listen is increased with 1

**Actual:**
User is redirected to Challenges page, counters for both Listen and Speak show 0 value

![Screenshot_2019-11-18 Common Voice by Mozilla](https://user-images.githubusercontent.com/5293100/69046797-82451800-0a02-11ea-90fc-56782ae8d67f.png)

![Screenshot_2019-11-18 Common Voice by Mozilla(1)](https://user-images.githubusercontent.com/5293100/69046798-82451800-0a02-11ea-9dd1-391e4c008f80.png)

**Comment by can-007** [comment] 2019-11-18 13:14
I think contribution counters are expected to be reset every week, and the vote was probably counted as the contribution of last week.
However, the points in the upright corner should increase with 1.
cc @mbransn for confirmation.

**Comment by mbransn** [comment] 2019-11-18 18:16
Expected:

- The weekly challenge counters (circles with set amount goal) should reset at the start of each week.
- The 'My points' overall challenge dashboard counter should not reset, it is accumulative.
- The overall contribution counter for speak and listen (existing in the site hearder) is still tied to clips and never resets.

**Comment by rileyjshaw** [comment] 2019-11-18 23:34
Since the `Week` counter increased by 1 between the first and second screenshot, my guess is that you tested this behaviour just as the staging challenge switched from Week 1 to Week 2 (which happened close to when this issue was logged). I can't reproduce on staging now that we're solidly in Week 2, so I'm going to close this.

Aside: it's strange that the sign up counter jumped from 38% to 70% between the screenshots. I just looked at the code, and I don't think the invite enrollment counter is resetting each week. I made a new issue for that: https://github.com/mozilla/voice-web/issues/2379

**Closed by rileyjshaw** 2019-11-18 23:34 UTC
Labels: Priority: P1, Type: Bug, voice-challenge
