### ISSUE TITLE
Some strings are untranslated

### ISSUE THREAD

**Issue by MekliCZ** [mozilla/voice-web#893] opened 2018-03-18 01:14 UTC
Some strings aren't fluentified:

Profile:
- [x] Genders
- [x] „Delete profile“
- [x] „Saved“
- [x] Delete profile dialog
- [x] Delete profile dialog buttons

Speak:
- [ ] App Store badge (but as far as I know, the iOS app will be deprecated soon)
- [x] „Create a profile“
- [x] „Why a profile?“

Validation:
- [x] „Sorry! We are validating...“

Footer:
- [x] Twitter text

**Comment by Djfe** [comment] 2018-03-29 12:41
- [ ] yes/no buttons (listening)
- [ ] projekt-status: language names ("English")
- [ ] text that pops up, when you click "why a profile"
- [ ] yes/no (download x GB dataset dialogue)
- [ ] "Mixed" (license type of tatoeba dataset)
- [ ] languages page
- [ ] accents (maybe?)
- [ ] "Exit Form" (create a profile, recording page)


someone should probably also check the code for html titles (hover) and aria texts

**Comment by Gregoor** [comment] 2018-04-18 19:07
Thanks for keepin track of all those missing strings. That was really helpful. I think I caught them all. Didn't touch accents yet, as I think we might redo that part anyway when the contribution part launches for other languages.

Feel free to reopen this if you find more instances of hardcoded sentences. And thanks again, it's been tremendously helpful!

**Comment by Djfe** [comment] 2018-04-19 01:14
the Mnemonics aren't translated, yet.

Yes in German means "Ja", so it starts with a J and not with a Y


The languages on the language page, should get the same translation as the languages on the front page
example:
English -> Englisch
The same goes for the language selection on the top right

Create a profile (button on the speak page and headline on the profile page)
"Close" (link that appears when you click on why a profile)

Age values -> teens, twenties, thirties etc.
sex value: other

text and buttons that appear, when you delete your profile

hover texts like "Press p to pause"

it would be nice if the string translations for 
"Review" and "Re-record" could be a bit longer so "Neu Aufnehmen" isn't broken up into two lines
If that's not possible, then I'll edit the translation.

**Comment by Djfe** [comment] 2018-04-19 01:15
I can't open this issue (missing permissions, I guess)

**Comment by Djfe** [comment] 2018-04-19 01:55
On the languages page:
German seems to be the default for all languages that aren't translated, yet.
(instead of english)
![screenshot](https://i.imgur.com/qRkHEIH.png)

**Comment by Djfe** [comment] 2018-04-19 01:57
also {$lang} in the long string shown in the screenshot isn't replaced by the name of the language
It just says "lang" in the middle of the sentence instead.

**Comment by Djfe** [comment] 2018-04-19 02:01
And two more strings:
![screenshot](https://i.imgur.com/aFRVS3e.png)

also:
why doesn't the language page link to Pontoon?

**Comment by Djfe** [comment] 2018-04-19 02:33
the get involved pop-up doesn't use this string:
https://pontoon.mozilla.org/de/common-voice/all-resources/?string=177871

**Comment by Djfe** [comment] 2018-04-19 02:53
Downloading datasets doesn't work on allizom, so I cannot check, whether this strings is translated correctly (whether the translation from Pontoon is used)
![screenshot](https://i.imgur.com/cMKJMFd.png)
https://pontoon.mozilla.org/de/common-voice/all-resources/?search=has+started&string=176037

**Comment by Djfe** [comment] 2018-04-19 03:00
the og:description and og:title meta tags, that social media use, aren't translated, yet.

**Comment by Djfe** [comment] 2018-04-19 03:05
``` Help teach machiness how real people speak, donate your voice at ```
The original string for twitter has a spelling error
``` machiness ```

**Comment by Djfe** [comment] 2018-04-19 03:29
the string data-download-no is ``` yes ``` atm. for some reason
https://pontoon.mozilla.org/de/common-voice/all-resources/?time=201803250706-201804190125&string=178217
But since it's currently unused that might not matter much anyway.

**Comment by Djfe** [comment] 2018-04-19 03:33
https://pontoon.mozilla.org/de/common-voice/all-resources/?time=201803250706-201804190125&string=178226
https://pontoon.mozilla.org/de/common-voice/all-resources/?time=201803250706-201804190125&string=178213

``` Keep the recordings ```
``` Delete my recording ```
Inconsistency, that cause Michael to translate this wrong at first: the vs my

**Comment by Djfe** [comment] 2018-04-19 05:34
I'm not sure, whether this string shows up anywhere, but I stumbled upon it, while viewing the code:
https://github.com/mozilla/voice-web/blob/84c1f9cb70d9b75b69a710a37f249548a4b7f2a8/web/src/components/pages/record/profile-actions.tsx#L87

**Comment by MekliCZ** [comment] 2018-04-19 06:03
Even I can't reopen the issue. @Gregoor, please? :)

**Comment by Gregoor** [comment] 2018-04-19 07:39
Wow, thanks for catching all that @Djfe. Where is my mind? 🙃 

> the Mnemonics aren't translated, yet.
>
> Yes in German means "Ja", so it starts with a J and not with a Y
I was wondering about that: Is there a language in which Yes, No or Record start with the same letter. I'd imagine the chances are quite high. If so, we need something more sophisticated here (maybe then also best to discuss it in a separate issue).

> The languages on the language page, should get the same translation as the languages on the front page
I took the time to do it right and [created a script](https://github.com/mozilla/voice-web/blob/7d3fb8fd14d20532a0fd51a4d2b314ff4f661da6/scripts/pontoon-language-to-ftl.js) that gets all the languages from Pontoon and adds them to the message file. Though we atm have to run that manually. Might be best to put that into some hook, so that when new languages are added to Pontoon, they're automatically picked up.

**Comment by Djfe** [comment] 2018-04-19 09:09
So it only shows up like this on allizom or is it a recent regression?
![screenshot](https://i.imgur.com/FEdpOB2.png)

I took the time to take an extensive look at every string to make sure :D
I hope that helps :)

I'll do so again, once you finished this batch 🗡 
Greetings!

**Comment by Gregoor** [comment] 2018-04-19 09:18
> So it only shows up like this on allizom or is it a recent regression?

Uuh yaiks! That is indeed a recent regression 🙈 I just pushed a fix, should be on staging soon.

> I hope that helps :)

It more than helps. It super helps 🙂

**Comment by Djfe** [comment] 2018-05-07 09:43
Took another look again, everything that's fixed is now striked through ;)
The remaining issues are above.

And I discovered another one: #986

**Comment by Gregoor** [comment] 2018-05-09 10:08
Unfortunately there's not much we can do about the meta tags atm, as most social sites afaik don't run JS. We can look into this if & when we look into Server Side Rendering #686 again.

The hover text for shortcut is fixed in the multi-lang branch #982

**Closed** 2018-08-21 15:43 UTC
