### ISSUE TITLE
"recording too long" warning trigger time too short.

### ISSUE THREAD

**Issue by iveskins** [mozilla/voice-web#779] opened 2017-12-15 11:57 UTC
I got this prompt
"The police was still interrogating witnesses of the rape when a mob outside began to practice lynch law."
I read it at a bit of a slow pace, but not unreasonable for the length of the words.. and then I got a "recording too long" message. 
If recording of that length are not useful for the dataset, then maybe these longer prompts should be removed?

**Comment by reinhart1010** [comment] 2017-12-17 03:22
If you are testing this in Chrome, this bug could be a duplicate of #770.

**Comment by iveskins** [comment] 2017-12-17 04:44
I am using chromium, .. I recorded a bit of a long sentence and then when I hit the button to stop I got the notification that I pasted in the title
isn't #770 about the "too short" message.. 
I am talking about the "too long" message. I think some of the sentences, with lots of word might take a while to say, and the too long warning will be triggered even if they are said at a normal pace.

**Comment by Gregoor** [comment] 2018-01-15 14:59
@kdavis-mozilla: Is there a hard-limit for the max length of the recording we'd want?

If so we should probably allow users to report sentences that can't reasonable be read in that time (related issue #278)

**Comment by kdavis-mozilla** [comment] 2018-01-15 15:04
No a hard limit; but, in practice maybe 10-15sec is the longest that's useful, a limit imposed by the GPU VRAM we use.

**Comment by MichaelNMaggs** [comment] 2018-01-15 16:26
Copying this across from #801 (closed as duplicate of this issue):

It's not possible to record some of the longer sentences, as the "recording was too long" message prevents it. One example sentence that I'm not able to record is this one:

_- "The closet door stuck a little as he pulled it open revealing a bare wooden floor covered on one side by a stack of old shoes boxes."_

I'm using Firefox Quantum 57.0.4 on a Mac, if that's helpful

**Comment by iveskins** [comment] 2018-01-16 13:09
[This paper ](http://asa.scitation.org/doi/full/10.1121/1.4929622) gives the average syllables per second of native english speakers as from 3 - 7 .. so .. to keep things comfortable under ten seconds, accounting for the slow down for unfamiliar words, or strange phrasing, international englishes... maybe no prompts over 30 syllables.?

e.g 
- "The closet door stuck a little as he pulled it open revealing a bare wooden floor covered on one side by a stack of old shoes boxes."
is 35 syllables.

maybe for simplicity sake .. average 1.66 syllables per word and say no prompts longer than .. 20ish words?

**Closed** 2018-01-30 15:36 UTC
