### ISSUE TITLE
Add instructions for classification

### ISSUE THREAD

**Issue by skorokithakis** [mozilla/voice-web#243] opened 2017-06-24 12:07 UTC
I tried to classify some sentences but wasn't sure what to do when people misread. For example, in one sentence, someone misread "in" for "is". Is that sentence supposed to be correct or not?

Some guidelines on the page would be great.

**Comment by kdavis-mozilla** [comment] 2017-06-24 12:14
If they don't read exactly the words in the sentence, then it should be counted as a "Nope"

**Comment by skorokithakis** [comment] 2017-06-24 12:15
Ah, good to know, thanks.

**Comment by DeathCamel57** [comment] 2017-07-26 00:41
#358 should help everyone with this question.

**Comment by mikehenrty** [comment] 2017-07-27 00:00
Duplicate of #273.

**Closed by mikehenrty** 2017-07-27 00:00 UTC
Labels: Priority: P2, Type: Enhancement
