### ISSUE TITLE
It would be nice to show stats on the website

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/voice-web#219] opened 2017-06-22 18:36 UTC
On the website, it would be great to see e.g. how many samples were recorded, and how many were verified (possibly live stats).

**Comment by kdavis-mozilla** [comment] 2017-06-22 18:41
Actually it's there but not called out as such, the red and green numbers at the top left of the screen.

I'll take this as a request to call out that info.

**Comment by mikehenrty** [comment] 2017-06-22 18:42
Hi @jankeromnes Thanks for the bug report! This is definitely on our "must do" list. We especially want to set specific goals around, for example, number of clips to record, and put a progress marker up on the website. Stay tuned!

**Comment by mikehenrty** [comment] 2017-07-25 21:58
Whoops, I forgot this bug existed when I filed #262. Since there's more discussion there, let's close this one.

Duplicate of #262.

**Closed by mikehenrty** 2017-07-25 21:58 UTC
Labels: Browser: All, OS: All, Priority: P3, Type: Enhancement
