### ISSUE TITLE
The website should explain more clearly how to re record in case of a failed attempt

### ISSUE THREAD

**Issue by xKeiro** [mozilla/voice-web#313] opened 2017-07-21 12:09 UTC
It would be nice if the website would explain more clearly how you can re record things. Heard several recordings where people messed up the sentence and finished it with some profanity.

**Comment by mikehenrty** [comment] 2017-07-21 14:15
Yeah, I've heard other's give this same feedback. The back arrow behaves a little weird if you just want to re-record. Let's try to address this all in #286.

Duplicate of #286.

**Comment by jdittrich** [comment] 2017-07-21 21:15
Hi @mikehenrty, please reopen. Sadly, this is a separate issue. At #286 I can try to replace some icons.  

In this case, we probably need an additional button, because you may want to do the following actions:

1. Finish/"OK" recording of the current recording ("I am fine with what I recorded right now")
2. Stop and re-record the *current* recording. ("I dislike with what I recorded right now")
3. Go back and re-record the *previous* recording ("I dislike with what I recorded previously")

Currently, only 3. and 1. are supported; However, the action 2. could also be assigned to the controls of 1 since it could mean "stop" (’cause I don’t like it)  or 3 (since it looks like undo)

**Comment by mikehenrty** [comment] 2017-07-23 13:24
Ok, I agree, let's re-examine this.

>     Finish/"OK" recording of the current recording ("I am fine with what I recorded right now")

I disagree with this part. We used to have one of these, and for the power user this only slowed things down. Since people who get to the record page record an average of 20 seconds, I'd rather optimize for that.

>     Stop and re-record the current recording. ("I dislike with what I recorded right now")
Agreed, let's add this. Perhaps a red X that shows up on the right when the user is currently recording.

>     Go back and re-record the previous recording ("I dislike with what I recorded previously")
Yup, let's keep this.

**Comment by jdittrich** [comment] 2017-07-23 15:17
>>    Finish/"OK" recording of the current recording ("I am fine with what I recorded right now")
>
> I disagree with this part. We used to have one of these, and for the power user this only slowed things > down.

I was not suggesting an additional button – currently the action that achieves this is re-clicking record – that’s fine. 

> Agreed, let's add this. Perhaps a red X that shows up on the right when the user is currently recording.

Yes – I wonder if we should just name this "retry this recording" (it depends if you have i18n in place or not); usually text is less ambiguous.

**Comment by mikehenrty** [comment] 2017-07-23 15:29
> Yes – I wonder if we should just name this "retry this recording" (it depends if you have i18n in place or not); usually text is less ambiguous.

We don't have i18n in place yet, but we will need to very soon.

**Comment by Gregoor** [comment] 2019-01-16 15:10
I think the new contribution page is better at this (at least I haven't heard any new complaints in this area). LMK if we should re-open this debate.

**Closed by Gregoor** 2019-01-16 15:10 UTC
