### ISSUE TITLE
The listening and judging or voting

### ISSUE THREAD

**Issue by tanmayameher** [mozilla/voice-web#314] opened 2017-07-21 12:53 UTC
Hey guys nice work.

I think the listen and vote or validating sentences is too abstract by a yes and no buttons.

I have started validating from yesterday and decide to do a 50 to 100 validation each day (if possible).
I choose to listen without looking at sentence first and i find out that sometimes it is not clear esp. from non-English and sometimes even fast English speaker. So, in such cases you should put at least a highlighting feature which part or word is not understood / clear or at least what percentage of the sentence is understood /clear, because putting them in a no section is really unjust. That's what your voice bot needs as an outlier test cases or for increasing the preciseness of the bot or whatever. :)

Then again, some people speak clearly but some background noises are added or they forget the word is in plural form like "houses" not "house" etc. or even they add some extra words like "also", "the" etc. Also, some people sing (rather speak) the sentence but correctly. :stuck_out_tongue_winking_eye: These sentence will fall into false positive if there is yes and no only. May be a not clear button would be nice.

PS: There are few people really (yes really) trying to screw this bot. They are putting whatever troll sentence into it though that would go into no section. Anyway, i thought you would like to know. :stuck_out_tongue_winking_eye:

Anyways, great work keep it up.
Thanks and Regards

**Comment by mikehenrty** [comment] 2017-07-21 14:21
> I have started validating from yesterday and decide to do a 50 to 100 validation each day (if possible).

You are a champion!

Thanks for your feedback about validation. From a data integrity standpoint, we only care is something exactly matches the sentence, otherwise it's far less useful to speech training algorithms. It's sad, but trolls and people who mispronounce a word are both marked with the same grade.

That said, I (and others) agree with you that the website does not make this clear. Let's use #273 to track that problem since there's already a long discussion there.

Duplicate of #273

**Closed by mikehenrty** 2017-07-21 14:21 UTC

**Comment by tanmayameher** [comment] 2017-07-22 06:37
oh a whole discussion is there. I lacked in good searching. sorry about duplicate post :)

**Comment by rugk** [comment] 2017-07-22 14:04
Just to confirm: When the thing is too quiet, what should we select right now? Yes or No?

I think this type of "issue" can be selected by automated systems and they could just "turn up the volume" and so the data could still be useful for training?

**Comment by rugk** [comment] 2017-07-22 14:39
Another question: Is it valid when two or more people are speaking/reading the sentence at the same time? (yeah, I heard that, and it was only slight trolling :laughing:, but to be fair, it is disallowed nowhere… )

**Comment by mikehenrty** [comment] 2017-07-23 14:28
> Just to confirm: When the thing is too quiet, what should we select right now? Yes or No?

If you can turn up the volume and understand what is said (and validate it), the answer is YES. If it's too quiet to be able to tell what is said, NO.

> Is it valid when two or more people are speaking/reading the sentence at the same time?

Ha! I would say no, but if you said yes it's no big deal :)
