### ISSUE TITLE
Keep asking for validate the same sentence

### ISSUE THREAD

**Issue by linediconsine** [mozilla/voice-web#351] opened 2017-07-24 20:02 UTC
HI, I was validating some sentence and the site after a while start to show me the same sentences with the same voice. It is stuck in a loop

Thank you
![screen shot 2017-07-24 at 4 00 10 pm](https://user-images.githubusercontent.com/1525362/28542193-56bdabee-7089-11e7-8f08-0885be183fa3.png)

**Comment by jf99** [comment] 2017-07-24 20:26
Duplicate of #344

**Closed** 2017-07-25 04:45 UTC
